import {
  CHATGPT_APP_NAME,
  CHATGPT_APP_VERSION,
  OAUTH_SCOPES,
  VOICE_RESULT_RESOURCE_URI,
} from "./constants.js";
import { jsonResponse, methodNotAllowed } from "./http.js";
import {
  authenticateAccessTokenWithEnv,
  authenticationRequiredToolResult,
  hasRequiredScopes,
} from "./oauth.js";
import {
  CHATGPT_TOOL_NAMES,
  ToolInputError,
  executeChatGptTool,
} from "./tools.js";
import { voiceResultResource } from "./ui.js";
import { toolDescriptors } from "./mcp-descriptors.js";

const SUPPORTED_PROTOCOL_VERSIONS = Object.freeze([
  "2025-11-25",
  "2025-06-18",
  "2025-03-26",
  "2024-11-05",
]);

const TOOL_SCOPES = Object.freeze({
  [CHATGPT_TOOL_NAMES.listVoices]: [OAUTH_SCOPES.read],
  [CHATGPT_TOOL_NAMES.getBalance]: [OAUTH_SCOPES.read],
  [CHATGPT_TOOL_NAMES.getHistory]: [OAUTH_SCOPES.read],
  [CHATGPT_TOOL_NAMES.generateVoice]: [OAUTH_SCOPES.generate],
});

export async function handleMcpRequest(request, env) {
  if (request.method !== "POST") {
    return methodNotAllowed(["POST"]);
  }

  const payload = await request.json().catch(() => null);
  if (payload == null) {
    return jsonResponse(
      rpcError(null, -32700, "Parse error"),
      400,
      mcpHeaders(),
    );
  }

  const origin = new URL(request.url).origin;
  const authentication = await authenticateAccessTokenWithEnv(
    request,
    env,
  ).catch((error) => {
    console.error("chatgpt access token lookup failed", error?.stack || error);
    return {
      ok: false,
      error: "invalid_token",
      description: "The access token could not be verified.",
    };
  });

  if (Array.isArray(payload)) {
    if (!payload.length) {
      return jsonResponse(
        rpcError(null, -32600, "Invalid Request"),
        400,
        mcpHeaders(),
      );
    }

    const responses = [];
    for (const message of payload) {
      const response = await handleRpcMessage(
        message,
        env,
        origin,
        authentication,
      );

      if (response) {
        responses.push(response);
      }
    }

    if (!responses.length) {
      return new Response(null, {
        status: 202,
        headers: mcpHeaders(),
      });
    }

    return jsonResponse(responses, 200, mcpHeaders());
  }

  const response = await handleRpcMessage(
    payload,
    env,
    origin,
    authentication,
  );

  if (!response) {
    return new Response(null, {
      status: 202,
      headers: mcpHeaders(),
    });
  }

  return jsonResponse(response, 200, mcpHeaders());
}

async function handleRpcMessage(message, env, origin, authentication) {
  if (!isRpcMessage(message)) {
    return rpcError(null, -32600, "Invalid Request");
  }

  const id = Object.prototype.hasOwnProperty.call(message, "id")
    ? message.id
    : undefined;
  const isNotification = id === undefined;

  try {
    if (message.method === "initialize") {
      return isNotification
        ? null
        : rpcResult(id, initializeResult(message.params));
    }

    if (
      message.method === "notifications/initialized" ||
      message.method === "notifications/cancelled"
    ) {
      return null;
    }

    if (message.method === "ping") {
      return isNotification ? null : rpcResult(id, {});
    }

    if (message.method === "tools/list") {
      return isNotification
        ? null
        : rpcResult(id, {
            tools: toolDescriptors(),
          });
    }

    if (message.method === "tools/call") {
      if (isNotification) {
        return null;
      }

      const result = await callTool(
        message.params,
        env,
        origin,
        authentication,
      );
      return rpcResult(id, result);
    }

    if (message.method === "resources/list") {
      return isNotification
        ? null
        : rpcResult(id, {
            resources: [
              {
                uri: VOICE_RESULT_RESOURCE_URI,
                name: "Vexa voice result",
                title: "Generated voice player",
                description: "Plays a voice generated by Vexa.",
                mimeType: "text/html;profile=mcp-app",
              },
            ],
          });
    }

    if (message.method === "resources/read") {
      if (isNotification) {
        return null;
      }

      const uri = String(message.params?.uri || "");
      if (uri !== VOICE_RESULT_RESOURCE_URI) {
        return rpcError(id, -32002, "Resource not found");
      }

      return rpcResult(id, voiceResultResource(origin));
    }

    if (message.method === "resources/templates/list") {
      return isNotification
        ? null
        : rpcResult(id, {
            resourceTemplates: [],
          });
    }

    if (message.method === "prompts/list") {
      return isNotification
        ? null
        : rpcResult(id, {
            prompts: [],
          });
    }

    return isNotification
      ? null
      : rpcError(id, -32601, "Method not found");
  } catch (error) {
    console.error("chatgpt mcp request failed", error?.stack || error);

    return isNotification
      ? null
      : rpcError(id, -32603, "Internal error");
  }
}

async function callTool(params, env, origin, authentication) {
  const toolName = String(params?.name || "");
  const requiredScopes = TOOL_SCOPES[toolName];

  if (!requiredScopes) {
    return toolError("Tool not found.");
  }

  if (!authentication.ok) {
    return authenticationRequiredToolResult(
      origin,
      requiredScopes,
      authentication,
    );
  }

  if (!hasRequiredScopes(authentication, requiredScopes)) {
    return authenticationRequiredToolResult(
      origin,
      requiredScopes,
      {
        error: "insufficient_scope",
        description: "Reconnect the app to grant the required permission.",
      },
    );
  }

  try {
    return await executeChatGptTool(
      toolName,
      params?.arguments,
      {
        env,
        origin,
        userId: authentication.userId,
      },
    );
  } catch (error) {
    if (error instanceof ToolInputError) {
      return toolError(error.message);
    }

    console.error("chatgpt tool execution failed", error?.stack || error);
    return toolError(
      error?.message || "The voice request could not be completed.",
    );
  }
}

function initializeResult(params) {
  const requestedVersion = String(params?.protocolVersion || "");
  const protocolVersion = SUPPORTED_PROTOCOL_VERSIONS.includes(requestedVersion)
    ? requestedVersion
    : SUPPORTED_PROTOCOL_VERSIONS[0];

  return {
    protocolVersion,
    capabilities: {
      tools: {
        listChanged: false,
      },
      resources: {
        subscribe: false,
        listChanged: false,
      },
    },
    serverInfo: {
      name: "vexa-voice",
      title: CHATGPT_APP_NAME,
      version: CHATGPT_APP_VERSION,
    },
    instructions:
      "Use list_voices before generation when the user has not named a voice. " +
      "Voice generation is billed in USD at $0.00017 per character. " +
      "Use get_balance before long generations when available.",
  };
}

function toolError(message) {
  return {
    isError: true,
    content: [
      {
        type: "text",
        text: String(message || "The tool request failed."),
      },
    ],
  };
}

function isRpcMessage(value) {
  return Boolean(
    value &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    value.jsonrpc === "2.0" &&
    typeof value.method === "string",
  );
}

function rpcResult(id, result) {
  return {
    jsonrpc: "2.0",
    id,
    result,
  };
}

function rpcError(id, code, message, data = undefined) {
  const error = {
    code,
    message,
  };

  if (data !== undefined) {
    error.data = data;
  }

  return {
    jsonrpc: "2.0",
    id,
    error,
  };
}

function mcpHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Expose-Headers": "WWW-Authenticate",
    "MCP-Protocol-Version": SUPPORTED_PROTOCOL_VERSIONS[0],
  };
}
