CREATE TABLE IF NOT EXISTS user_state (
  user_id TEXT PRIMARY KEY,
  voice TEXT NOT NULL DEFAULT 'Nora',
  output TEXT NOT NULL DEFAULT 'MP3',
  page INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS demo_cache (
  voice TEXT PRIMARY KEY,
  audio_base64 TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
