name = "ai-configa"
main = "src/worker.js"
compatibility_date = "2026-05-28"
workers_dev = true
preview_urls = true

# Secrets are not written here. Set them with:
# npx wrangler secret put BOT_TOKEN
# npx wrangler secret put ELEVEN_API

[[d1_databases]]
binding = "DB"
database_name = "ai-configa-db"
database_id = "33c8cf30-4daa-498a-8706-d457869f5d25"
