CREATE TABLE IF NOT EXISTS pending_payments (
  user_id TEXT PRIMARY KEY,
  package_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
