export const GITHUB_CLIENT_JS = `
(function(){
  if(window.__vexaGithubClientLoaded)return;
  window.__vexaGithubClientLoaded=true;
  var tg=window.Telegram&&window.Telegram.WebApp;
  var initData=(tg&&tg.initData)||'';
  var state={connected:false,login:'',repository:null,repositories:[],authorizeUrl:'',pendingConnect:false,busy:false};
  function q(id){return document.getElementById(id)}
  function api(path,body){return fetch(path,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},cache:'no-store',body:JSON.stringify(Object.assign({initData:initData},body||{}))}).then(async function(response){var data=await response.json().catch(function(){return{error:'Invalid response'}});if(!response.ok)throw new Error(data.error||'Request failed');return data})}
  function shortRepo(fullName){var parts=String(fullName||'').split('/');return parts[parts.length-1]||'GitHub'}
  function inject(){
    var tools=document.querySelector('.mode-tools');
    if(!tools)return;
    var button=q('aiChatGithubButton');
    if(!button){button=document.createElement('button');button.id='aiChatGithubButton';button.type='button';button.className='ai-github-button';button.setAttribute('aria-label','Connect GitHub repository');button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 .8a11.4 11.4 0 0 0-3.6 22.2c.6.1.8-.2.8-.6v-2.2c-3.3.7-4-1.4-4-1.4-.5-1.4-1.3-1.7-1.3-1.7-1.1-.8.1-.8.1-.8 1.2.1 1.9 1.3 1.9 1.3 1.1 1.9 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-5.7 0-1.3.5-2.3 1.2-3.1-.1-.3-.5-1.6.1-3.1 0 0 1-.3 3.1 1.2a10.8 10.8 0 0 1 5.7 0C14.9 5 16 5.3 16 5.3c.6 1.5.2 2.8.1 3.1.8.8 1.2 1.8 1.2 3.1 0 4.4-2.8 5.4-5.5 5.7.4.4.8 1.1.8 2.2v3c0 .4.2.7.8.6A11.4 11.4 0 0 0 12 .8Z"/></svg><span class="ai-github-button-label">GitHub</span>';tools.insertBefore(button,tools.firstChild)}
    var modal=document.createElement('div');modal.id='aiChatGithubModal';modal.className='ai-github-backdrop';modal.setAttribute('aria-hidden','true');
    modal.innerHTML='<section class="ai-github-sheet" role="dialog" aria-modal="true" aria-labelledby="aiGithubTitle"><header class="ai-github-head"><div class="ai-github-title"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 .8a11.4 11.4 0 0 0-3.6 22.2c.6.1.8-.2.8-.6v-2.2c-3.3.7-4-1.4-4-1.4-.5-1.4-1.3-1.7-1.3-1.7-1.1-.8.1-.8.1-.8 1.2.1 1.9 1.3 1.9 1.3 1.1 1.9 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-5.7 0-1.3.5-2.3 1.2-3.1-.1-.3-.5-1.6.1-3.1 0 0 1-.3 3.1 1.2a10.8 10.8 0 0 1 5.7 0C14.9 5 16 5.3 16 5.3c.6 1.5.2 2.8.1 3.1.8.8 1.2 1.8 1.2 3.1 0 4.4-2.8 5.4-5.5 5.7.4.4.8 1.1.8 2.2v3c0 .4.2.7.8.6A11.4 11.4 0 0 0 12 .8Z"/></svg><strong id="aiGithubTitle">GitHub</strong></div><button id="aiGithubClose" class="ai-github-close" type="button" aria-label="Close">×</button></header><div id="aiGithubBody" class="ai-github-body"><div class="ai-github-loading">Loading…</div></div></section>';
    document.body.appendChild(modal);
    button.addEventListener('click',openModal);q('aiGithubClose').addEventListener('click',closeModal);modal.addEventListener('pointerdown',function(event){if(event.target===modal)closeModal()});
  }
  function updateButton(){var button=q('aiChatGithubButton');if(!button)return;button.classList.toggle('connected',!!state.repository);button.querySelector('.ai-github-button-label').textContent=state.repository?shortRepo(state.repository.fullName):'GitHub';button.setAttribute('aria-label',state.repository?'Connected repository '+state.repository.fullName:'Connect GitHub repository')}
  function showError(message){var node=q('aiGithubError');if(!node)return;node.textContent=String(message||'GitHub request failed');node.classList.add('show')}
  function openModal(){var modal=q('aiChatGithubModal');if(!modal)return;modal.classList.add('open');modal.setAttribute('aria-hidden','false');loadRepositories()}
  function closeModal(){var modal=q('aiChatGithubModal');if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
  function render(){
    updateButton();var body=q('aiGithubBody');if(!body)return;body.replaceChildren();
    var error=document.createElement('div');error.id='aiGithubError';error.className='ai-github-error';body.appendChild(error);
    if(!state.connected){var copy=document.createElement('p');copy.className='ai-github-copy';copy.textContent='Connect a repository so Vexa can read your code and create changes on a separate branch.';body.appendChild(copy);var connect=document.createElement('button');connect.type='button';connect.className='ai-github-primary';connect.textContent='Connect GitHub';connect.addEventListener('click',connectGithub);body.appendChild(connect);return}
    var account=document.createElement('div');account.className='ai-github-account';var label=document.createElement('span');label.textContent='Connected as';var login=document.createElement('strong');login.textContent=state.login||'GitHub user';account.appendChild(label);account.appendChild(login);body.appendChild(account);
    if(!state.repositories.length){var empty=document.createElement('div');empty.className='ai-github-empty';empty.textContent='No repositories are available. Install the GitHub App on a repository, then return here.';body.appendChild(empty);var install=document.createElement('button');install.type='button';install.className='ai-github-primary';install.textContent='Manage GitHub access';install.addEventListener('click',connectGithub);body.appendChild(install)}else{var repos=document.createElement('div');repos.className='ai-github-repos';state.repositories.forEach(function(repo){var selected=!!(state.repository&&state.repository.fullName===repo.fullName);var button=document.createElement('button');button.type='button';button.className='ai-github-repo'+(selected?' selected':'');button.innerHTML='<span class="ai-github-repo-icon" aria-hidden="true">'+(repo.private?'●':'○')+'</span>';var text=document.createElement('span');text.className='ai-github-repo-copy';var name=document.createElement('strong');name.textContent=repo.fullName;var branch=document.createElement('small');branch.textContent=repo.defaultBranch+(selected?' · Connected':'');text.appendChild(name);text.appendChild(branch);button.appendChild(text);button.addEventListener('click',function(){selectRepo(repo)});repos.appendChild(button)});body.appendChild(repos)}
    var disconnect=document.createElement('button');disconnect.type='button';disconnect.className='ai-github-secondary danger';disconnect.textContent='Disconnect GitHub';disconnect.addEventListener('click',disconnectGithub);body.appendChild(disconnect);
  }
  async function refreshStatus(){try{var data=await api('/mini-app/api/github/status',{});state.connected=!!data.connected;state.login=String(data.login||'');state.repository=data.repository||null;updateButton()}catch(error){updateButton()}}
  async function loadRepositories(){var body=q('aiGithubBody');if(body)body.innerHTML='<div class="ai-github-loading">Loading repositories…</div>';try{var data=await api('/mini-app/api/github/repositories',{});state.connected=!!data.connected;state.login=String(data.login||'');state.repository=data.repository||null;state.repositories=Array.isArray(data.repositories)?data.repositories:[];state.authorizeUrl=String(data.authorizeUrl||'');render()}catch(error){state.repositories=[];state.authorizeUrl='';render();showError(error.message)}}
  function connectGithub(){if(state.busy)return;var authorizeUrl=String(state.authorizeUrl||'');var authorize=null;try{authorize=new URL(authorizeUrl)}catch(error){}if(!authorize||authorize.protocol!=='https:'||authorize.hostname!=='github.com'||authorize.pathname!=='/login/oauth/authorize'){showError('GitHub connection is not ready. Close this window and try again.');return}state.pendingConnect=true;window.location.assign(authorizeUrl)}
  async function selectRepo(repo){if(state.busy)return;state.busy=true;try{var data=await api('/mini-app/api/github/select',{installationId:repo.installationId,repoId:repo.id});state.repository=data.repository||repo;render();if(tg&&tg.HapticFeedback)try{tg.HapticFeedback.notificationOccurred('success')}catch(error){}}catch(error){showError(error.message)}finally{state.busy=false}}
  async function disconnectGithub(){if(state.busy)return;state.busy=true;try{await api('/mini-app/api/github/disconnect',{});state.connected=false;state.login='';state.repository=null;state.repositories=[];state.authorizeUrl='';render()}catch(error){showError(error.message)}finally{state.busy=false}}
  document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible'&&state.pendingConnect){state.pendingConnect=false;loadRepositories()}});
  function start(){inject();refreshStatus()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
`;
