export const GITHUB_STYLES = `
.ai-chat-menu-backdrop{background:rgba(0,0,0,.34)!important;backdrop-filter:blur(2px)!important;-webkit-backdrop-filter:blur(2px)!important}
.ai-chat-menu-panel{left:12px!important;top:calc(52px + env(safe-area-inset-top))!important;bottom:auto!important;width:min(74vw,288px)!important;max-height:calc(var(--ai-chat-page-height) - 64px - env(safe-area-inset-top) - env(safe-area-inset-bottom));padding:12px!important;border:0!important;border-radius:22px!important;background:var(--ticket-glass-bg)!important;box-shadow:var(--ticket-glass-shadow),0 24px 60px rgba(0,0,0,.34)!important;backdrop-filter:blur(10px) saturate(1.12)!important;-webkit-backdrop-filter:blur(10px) saturate(1.12)!important;transform:translate3d(-18px,0,0) scale(.97)!important;opacity:0;transform-origin:top left;transition:transform .3s cubic-bezier(.16,1,.3,1),opacity .2s ease!important}
.ai-chat-menu-backdrop.open .ai-chat-menu-panel{transform:none!important;opacity:1}
.ai-chat-menu-head{padding:1px 2px 12px!important}.ai-chat-menu-head>div{gap:0!important}.ai-chat-menu-head small{display:none!important}.ai-chat-menu-head strong{font-size:16px!important;font-weight:680!important;letter-spacing:-.025em!important}.ai-chat-menu-head button{width:28px!important;height:28px!important;border-radius:10px!important;background:transparent!important;color:rgba(255,255,255,.48)!important;font-size:20px!important}
.ai-chat-menu-section{padding:10px 0!important;border-top:1px solid rgba(255,255,255,.075)!important}.ai-chat-menu-section>p{margin:0 3px 7px!important;color:rgba(255,255,255,.34)!important;font-size:9px!important;font-weight:650!important;letter-spacing:.06em!important;text-transform:none!important}
.ai-chat-model-grid{gap:2px!important}.ai-chat-model-grid .model-option{min-height:46px!important;padding:7px 9px!important;border:0!important;border-radius:12px!important;background:transparent!important;color:rgba(255,255,255,.58)!important;box-shadow:none!important}.ai-chat-model-grid .model-option.active{background:rgba(255,255,255,.075)!important;color:#fff!important;box-shadow:none!important}.ai-chat-model-grid .model-option span{gap:2px!important}.ai-chat-model-grid .model-option strong{font-size:13px!important;font-weight:650!important}.ai-chat-model-grid .model-option strong em{font-size:8px!important;color:rgba(255,255,255,.3)!important}.ai-chat-model-grid .model-option small{font-size:9px!important;color:rgba(255,255,255,.3)!important}.ai-chat-model-grid .model-option>b{width:6px!important;height:6px!important;border:1px solid rgba(255,255,255,.22)!important;background:transparent!important;box-shadow:none!important}.ai-chat-model-grid .model-option.active>b{border-color:rgba(255,255,255,.82)!important;background:rgba(255,255,255,.82)!important;box-shadow:none!important}
.ai-chat-effort-grid{gap:2px!important;padding:3px!important;border-radius:12px!important;background:rgba(255,255,255,.035)!important}.ai-chat-effort-grid button{height:31px!important;border-radius:9px!important;color:rgba(255,255,255,.38)!important;font-size:10px!important;font-weight:620!important}.ai-chat-effort-grid button.active{background:rgba(255,255,255,.085)!important;color:#fff!important;box-shadow:none!important}
.ai-chat-menu-github-slot .ai-github-button{width:100%!important;max-width:none!important;height:42px!important;min-height:42px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:9px!important;padding:0 8px!important;border:0!important;border-radius:11px!important;background:transparent!important;color:rgba(255,255,255,.78)!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;font-size:12px!important;font-weight:620!important}.ai-chat-menu-github-slot .ai-github-button:active{transform:scale(.985)!important;background:rgba(255,255,255,.055)!important}.ai-chat-menu-github-slot .ai-github-button svg{width:17px!important;height:17px!important;flex:0 0 17px!important;fill:currentColor!important}.ai-chat-menu-github-slot .ai-github-button-label{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ai-chat-menu-chevron{margin-left:auto!important;color:rgba(255,255,255,.28)!important;font-size:20px!important;font-weight:300!important}
.ai-chat-memory-card{margin:0!important;padding:11px 2px 2px!important;border:0!important;border-top:1px solid rgba(255,255,255,.075)!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}.ai-chat-memory-head strong{font-size:11px!important;font-weight:650!important}.ai-chat-memory-head small{font-size:8px!important;color:rgba(255,255,255,.3)!important}.ai-chat-memory-head button{padding:5px 4px!important;border-radius:7px!important;background:transparent!important;color:rgba(255,255,255,.38)!important;font-size:9px!important}.ai-chat-memory-bar{height:3px!important;margin-top:10px!important;background:rgba(255,255,255,.065)!important}.ai-chat-memory-bar span{background:rgba(255,255,255,.72)!important;box-shadow:none!important}.ai-chat-memory-usage{margin-top:6px!important;color:rgba(255,255,255,.28)!important;font-size:8px!important}
#aiChatMenuPanel.github-view>.ai-chat-menu-head,#aiChatMenuPanel.github-view>.ai-chat-menu-section,#aiChatMenuPanel.github-view>.ai-chat-memory-card{display:none!important}
.ai-github-inline{display:none;min-width:0}.ai-github-inline[aria-hidden=false]{display:block;animation:aiGithubInlineIn .24s cubic-bezier(.16,1,.3,1) both}@keyframes aiGithubInlineIn{from{opacity:0;transform:translateX(8px)}to{opacity:1;transform:none}}
.ai-github-inline-head{display:flex;align-items:center;gap:8px;padding:1px 0 11px;border-bottom:1px solid rgba(255,255,255,.075)}.ai-github-back{width:28px;height:28px;flex:0 0 28px;display:grid;place-items:center;padding:0;border-radius:9px;background:transparent;color:rgba(255,255,255,.55)}.ai-github-back:active{background:rgba(255,255,255,.055)}.ai-github-back svg{width:16px;height:16px}.ai-github-inline-title{min-width:0;display:flex;align-items:center;gap:8px}.ai-github-inline-title>svg{width:18px;height:18px;flex:0 0 18px;fill:#fff}.ai-github-inline-title>span{min-width:0;display:grid;gap:1px}.ai-github-inline-title strong{font-size:13px;font-weight:660;letter-spacing:-.018em}.ai-github-inline-title small{max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:rgba(255,255,255,.3);font-size:8px;font-weight:520}
.ai-github-body{padding:8px 0 0!important;overflow:visible!important}.ai-github-copy{margin:2px 3px 11px!important;color:rgba(255,255,255,.42)!important;font-size:10px!important;line-height:1.45!important}.ai-github-primary,.ai-github-secondary,.ai-github-repo{width:100%;border:0;font:600 11px/1.2 var(--font-main);cursor:pointer}.ai-github-primary{min-height:40px;border-radius:11px;background:rgba(255,255,255,.085);color:#fff}.ai-github-primary:active{background:rgba(255,255,255,.12)}.ai-github-repos{display:grid;gap:2px}.ai-github-repo{min-height:48px;display:flex;align-items:center;gap:8px;padding:7px 8px;text-align:left;border-radius:11px;background:transparent;color:rgba(255,255,255,.7);transition:background .16s ease,transform .16s ease}.ai-github-repo:active{transform:scale(.985);background:rgba(255,255,255,.045)}.ai-github-repo.selected{background:rgba(255,255,255,.075);color:#fff}.ai-github-repo-copy{min-width:0;display:grid;gap:2px;flex:1}.ai-github-repo-copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;font-weight:650}.ai-github-repo-copy small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:rgba(255,255,255,.28);font-size:8px;font-weight:500}.ai-github-repo-check{width:20px;height:20px;flex:0 0 20px;display:grid;place-items:center;color:rgba(255,255,255,.8);opacity:0}.ai-github-repo-check svg{width:14px;height:14px}.ai-github-repo.selected .ai-github-repo-check{opacity:1}.ai-github-secondary{min-height:34px;margin-top:8px;border-top:1px solid rgba(255,255,255,.065);border-radius:0;background:transparent;color:rgba(255,255,255,.32)}.ai-github-secondary.danger{color:rgba(255,255,255,.32)}.ai-github-empty,.ai-github-loading{padding:20px 8px;text-align:center;color:rgba(255,255,255,.32);font-size:9px;line-height:1.4}.ai-github-error{display:none;margin:0 0 8px;padding:8px 9px;border:1px solid rgba(255,255,255,.075);border-radius:9px;background:rgba(255,255,255,.035);color:rgba(255,255,255,.58);font-size:9px;line-height:1.4}.ai-github-error.show{display:block}
#aiThinkingRow .ai-thinking-head{min-height:44px;gap:10px}
#aiThinkingRow .ai-thinking-loader{width:44px;height:44px;flex:0 0 44px;border:0;border-radius:0;background:transparent;box-shadow:none;transition:none}
#aiThinkingRow .ai-thinking-loader .ai-thinking-orb{display:block;width:44px;height:44px;flex-basis:44px;filter:drop-shadow(0 0 10px rgba(190,145,255,.16));animation:aiOrbReveal .78s cubic-bezier(.16,1,.3,1) both,aiOrbBreathe 2.8s ease-in-out .78s infinite}
#aiThinkingRow .ai-thinking-loader::after{content:none;display:none}
#aiThinkingRow .ai-thinking-label{font-size:15px;font-weight:480;line-height:normal;letter-spacing:-.018em;color:transparent;background:linear-gradient(100deg,rgba(255,255,255,.36) 18%,rgba(255,255,255,.92) 43%,rgba(211,180,255,.88) 52%,rgba(255,255,255,.46) 72%);background-size:240% 100%;background-position:100% 50%;-webkit-background-clip:text;background-clip:text;text-shadow:0 0 18px rgba(190,145,255,.08);animation:aiThinkingShine 2.25s ease-in-out .32s infinite}
#aiThinkingRow[data-state=searching] .ai-thinking-label{background-image:linear-gradient(100deg,rgba(255,255,255,.34) 18%,rgba(255,255,255,.78) 48%,rgba(255,255,255,.4) 76%);text-shadow:none}
.ai-coding-preview-title i{color:#3fb950!important}.ai-coding-preview-title em{color:#f85149!important}.ai-diff-stats .added{color:#3fb950!important}.ai-diff-stats .removed{color:#f85149!important}.ai-diff-line.add{background:rgba(46,160,67,.12)!important}.ai-diff-line.add>i{color:rgba(126,231,135,.58)!important}.ai-diff-line.add>b,.ai-diff-line.add>code{color:#7ee787!important}.ai-diff-line.remove{background:rgba(248,81,73,.12)!important}.ai-diff-line.remove>i{color:rgba(255,161,152,.58)!important}.ai-diff-line.remove>b,.ai-diff-line.remove>code{color:#ffa198!important}.ai-coding-result-stats .added b{color:#3fb950!important}.ai-coding-result-stats .removed b{color:#f85149!important}.ai-coding-result-link{display:none!important}
.ai-chat-head{top:calc(41px + env(safe-area-inset-top))!important}
.ai-chat-head::before{top:calc(-41px - env(safe-area-inset-top))!important}
.ai-chat-messages{margin-top:calc(107px + env(safe-area-inset-top))!important;padding-top:0!important;scroll-padding-top:18px!important}
.ai-chat-message.assistant+.ai-chat-message.user{margin-top:36px!important}
@media(max-width:360px){.ai-chat-menu-panel{width:min(78vw,278px)!important;left:10px!important}}
`;