import { VOICE_NAMES, VOICES } from "../voices.js";

const VOICE_ROWS = VOICE_NAMES.map((name) => {
  const voiceId = VOICES[name];
  return `<div class="voice-option" data-voice-row="${voiceId}"><span class="voice-avatar" aria-hidden="true"><span class="voice-avatar-image"></span></span><button class="voice-select${name === "Liam" ? " active" : ""}" data-voice="${voiceId}" data-voice-name="${name}" type="button"><span>${name}</span></button><button class="voice-preview" data-action="preview-voice" data-preview-voice="${voiceId}" data-preview-name="${name}" type="button" aria-label="Play ${name} demo"><span class="voice-preview-icon">▶</span></button></div>`;
}).join("");

export const MINI_APP_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover"/>
  <meta name="theme-color" content="#000000"/>
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"/>
  <meta http-equiv="Pragma" content="no-cache"/>
  <meta http-equiv="Expires" content="0"/>
  <title>Vexa Voice</title>
  <link rel="stylesheet" href="/mini-app/styles.css?v=20260720-24"/>
</head>
<body>
  <main class="app">
    <section id="flow" class="view active">
      <div class="tts-page">
        <div class="tts-head">
          <div class="credit-tools"><button id="voiceSettingsButton" class="voice-settings-button" data-action="open-voice-settings" type="button" aria-label="Voice settings"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 0 0-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 0 0-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 0 0-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 0 0-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 0 0 1.066-2.573c-.94-1.543.826-3.31 2.37-2.37a1.724 1.724 0 0 0 2.572-1.065Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><circle cx="12" cy="12" r="3" stroke="currentColor" stroke-width="1.75"/></svg></button><div class="credit-pill"><span id="balance">—</span><span>credits</span></div></div>
          <div class="mode-tools"><div id="voiceWrap" class="voice-wrap">
            <button class="voice-btn" data-action="toggle-voice" type="button">
              <span id="voiceButtonAvatar" class="voice-button-avatar" aria-hidden="true"></span>
              <span id="voiceLabel">Liam</span>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </button>
            <div class="voice-menu">${VOICE_ROWS}</div>
          </div><button id="modeToggle" class="mode-toggle" data-action="toggle-creation-mode" type="button" aria-label="Switch to image creation" aria-pressed="false"><svg class="mode-image-icon" width="19" height="19" viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="3.25" y="4.25" width="17.5" height="15.5" rx="4.25" stroke="currentColor" stroke-width="1.7"/><circle cx="8.3" cy="9" r="1.55" stroke="currentColor" stroke-width="1.55"/><path d="m5.8 17 4.15-4.15a1.4 1.4 0 0 1 1.98 0l1.55 1.55 1.25-1.25a1.4 1.4 0 0 1 1.98 0L19 15.45" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/><path d="M18.2 2.7v3M16.7 4.2h3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg><svg class="mode-voice-icon" width="19" height="19" viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="8.2" y="3" width="7.6" height="12" rx="3.8" stroke="currentColor" stroke-width="1.75"/><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0M12 18v3M8.8 21h6.4" stroke="currentColor" stroke-width="1.75" stroke-linecap="round"/></svg></button></div>
        </div>
        <div class="tts-area">
          <div class="tts-label">Text</div>
          <textarea id="ttsText" placeholder="Type something"></textarea>
        </div>
        <button class="keyboard-dismiss" data-action="dismiss-keyboard" type="button" aria-label="Hide keyboard"><svg width="22" height="22" viewBox="0 0 24 24" fill="none"><path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
        <div class="tts-bottom">
          <div class="player-history-row">
            <div id="wavePlayer" class="wave-player">
            <button id="wavePlay" class="wave-play" data-action="play-tts" type="button" aria-label="Play audio"><span class="wave-play-shape" aria-hidden="true"><svg class="wave-play-icon" viewBox="0 0 24 24" style="stroke:none"><path d="M6.2 2.8C4.7 1.9 2.8 3 2.8 4.75v14.5c0 1.75 1.9 2.85 3.4 1.95l13.8-8.1c1.6-.95 1.6-1.25 0-2.2z"/></svg><span class="wave-pause-icon"><i></i><i></i></span></span></button>
            <svg class="wave-svg" viewBox="0 0 240 44" preserveAspectRatio="none" aria-hidden="true"><rect x="2.0" y="15.0" width="3.2" height="14" rx="1.6"/><rect x="9.6" y="10.0" width="3.2" height="24" rx="1.6"/><rect x="17.2" y="16.5" width="3.2" height="11" rx="1.6"/><rect x="24.8" y="7.0" width="3.2" height="30" rx="1.6"/><rect x="32.4" y="13.0" width="3.2" height="18" rx="1.6"/><rect x="40.0" y="5.0" width="3.2" height="34" rx="1.6"/><rect x="47.6" y="16.0" width="3.2" height="12" rx="1.6"/><rect x="55.2" y="8.0" width="3.2" height="28" rx="1.6"/><rect x="62.8" y="12.0" width="3.2" height="20" rx="1.6"/><rect x="70.4" y="4.0" width="3.2" height="36" rx="1.6"/><rect x="78.0" y="14.5" width="3.2" height="15" rx="1.6"/><rect x="85.6" y="9.0" width="3.2" height="26" rx="1.6"/><rect x="93.2" y="6.0" width="3.2" height="32" rx="1.6"/><rect x="100.8" y="15.5" width="3.2" height="13" rx="1.6"/><rect x="108.4" y="10.5" width="3.2" height="23" rx="1.6"/><rect x="116.0" y="3.0" width="3.2" height="38" rx="1.6"/><rect x="123.6" y="10.5" width="3.2" height="23" rx="1.6"/><rect x="131.2" y="15.5" width="3.2" height="13" rx="1.6"/><rect x="138.8" y="6.0" width="3.2" height="32" rx="1.6"/><rect x="146.4" y="9.0" width="3.2" height="26" rx="1.6"/><rect x="154.0" y="14.5" width="3.2" height="15" rx="1.6"/><rect x="161.6" y="4.0" width="3.2" height="36" rx="1.6"/><rect x="169.2" y="12.0" width="3.2" height="20" rx="1.6"/><rect x="176.8" y="8.0" width="3.2" height="28" rx="1.6"/><rect x="184.4" y="16.0" width="3.2" height="12" rx="1.6"/><rect x="192.0" y="5.0" width="3.2" height="34" rx="1.6"/><rect x="199.6" y="13.0" width="3.2" height="18" rx="1.6"/><rect x="207.2" y="7.0" width="3.2" height="30" rx="1.6"/><rect x="214.8" y="16.5" width="3.2" height="11" rx="1.6"/><rect x="222.4" y="10.0" width="3.2" height="24" rx="1.6"/><rect x="230.0" y="15.0" width="3.2" height="14" rx="1.6"/></svg>
            <span class="wave-time" id="waveTime">0:00</span>
            <button id="waveShare" class="wave-share" data-action="share-tts" type="button" aria-label="Share audio"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 16V4m0 0L7.5 8.5M12 4l4.5 4.5M5 13.5v4A2.5 2.5 0 0 0 7.5 20h9a2.5 2.5 0 0 0 2.5-2.5v-4" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
            </div>
            <button id="historyButton" class="history-button" data-action="open-history" type="button" aria-label="Open history"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4.6 8.2A8.2 8.2 0 1 1 4 13" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="M4.6 8.2V4.6M4.6 8.2H8.2M12 7.8v4.6l3.1 1.8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
          </div>
          <div class="tts-generate-row">
            <button id="convertButton" class="tts-generate" data-action="generate-tts" type="button">Generate Voice</button>
            <span class="char-count-wrap"><button class="char-warning" id="ttsCharWarning" data-action="open-char-limit" type="button" aria-label="Text length warning"><span>!</span></button><span class="char-count" id="ttsCharCount">0 characters</span></span>
          </div>
          <audio id="ttsAudio" class="tts-hidden-audio"></audio>
          <audio id="voicePreviewAudio" class="tts-hidden-audio"></audio>
          <audio id="historyAudio" class="tts-hidden-audio"></audio>
        </div>
        <section id="imageWorkspace" class="image-workspace" aria-hidden="true">
          <header class="image-intro"><div class="image-kicker-row"><span class="image-kicker">CREATE</span><span id="imageCreditNote" class="image-credit-note">188 credits per image</span></div><h1>Imagine anything</h1><p>Describe a new image, or add one and tell us exactly what to change</p></header>
          <div class="image-composer">
            <label class="image-prompt-label" for="imagePrompt">Prompt</label>
            <textarea id="imagePrompt" maxlength="2000" placeholder="Describe the image you want to create"></textarea>
            <div class="image-composer-foot"><span id="imagePromptCount">0 / 2000</span><div class="image-composer-tools"><div id="imageSizePicker" class="image-size-picker"><button id="imageSizeToggle" class="image-size-toggle" data-action="toggle-image-size" type="button" aria-label="Image size: Square" aria-expanded="false"><span id="selectedSizeShape" class="size-shape size-square" aria-hidden="true"></span></button><div class="image-size-menu" role="menu" aria-label="Choose output size">
              <button class="image-size-option active" data-action="select-image-size" data-image-size="1024x1024" data-size-name="Square" type="button" role="menuitem" aria-pressed="true"><span class="size-shape size-square" aria-hidden="true"></span><span><strong>Square</strong><small>1:1 · 1024×1024</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1024x1280" data-size-name="Social portrait" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-portrait" aria-hidden="true"></span><span><strong>Social portrait</strong><small>4:5 · 1024×1280</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="960x1344" data-size-name="Photo portrait" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-portrait" aria-hidden="true"></span><span><strong>Photo portrait</strong><small>5:7 · 960×1344</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1152x1536" data-size-name="Classic portrait" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-portrait" aria-hidden="true"></span><span><strong>Classic portrait</strong><small>3:4 · 1152×1536</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1024x1536" data-size-name="Portrait" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-portrait" aria-hidden="true"></span><span><strong>Portrait</strong><small>2:3 · 1024×1536</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1152x2048" data-size-name="Story" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-tall" aria-hidden="true"></span><span><strong>Story</strong><small>9:16 · 1152×2048</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="768x1792" data-size-name="Mobile tall" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-tall" aria-hidden="true"></span><span><strong>Mobile tall</strong><small>9:21 · 768×1792</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1024x2048" data-size-name="Tall" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-tall" aria-hidden="true"></span><span><strong>Tall</strong><small>1:2 · 1024×2048</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="864x2592" data-size-name="Ultra tall" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-ultra-tall" aria-hidden="true"></span><span><strong>Ultra tall</strong><small>1:3 · 864×2592</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1280x1024" data-size-name="Social landscape" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-landscape" aria-hidden="true"></span><span><strong>Social landscape</strong><small>5:4 · 1280×1024</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1344x960" data-size-name="Photo landscape" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-landscape" aria-hidden="true"></span><span><strong>Photo landscape</strong><small>7:5 · 1344×960</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1536x1152" data-size-name="Classic landscape" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-landscape" aria-hidden="true"></span><span><strong>Classic landscape</strong><small>4:3 · 1536×1152</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1536x1024" data-size-name="Wide" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-landscape" aria-hidden="true"></span><span><strong>Wide</strong><small>3:2 · 1536×1024</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="2048x1152" data-size-name="Cinema" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-wide" aria-hidden="true"></span><span><strong>Cinema</strong><small>16:9 · 2048×1152</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="1792x768" data-size-name="Ultrawide" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-wide" aria-hidden="true"></span><span><strong>Ultrawide</strong><small>21:9 · 1792×768</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="2048x1024" data-size-name="Panorama" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-wide" aria-hidden="true"></span><span><strong>Panorama</strong><small>2:1 · 2048×1024</small></span></button>
              <button class="image-size-option" data-action="select-image-size" data-image-size="2592x864" data-size-name="Banner" type="button" role="menuitem" aria-pressed="false"><span class="size-shape size-ultra-wide" aria-hidden="true"></span><span><strong>Banner</strong><small>3:1 · 2592×864</small></span></button>
            </div></div><button class="image-upload-trigger" data-action="pick-image" type="button"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 16V4m0 0L7.5 8.5M12 4l4.5 4.5M5 13.5v4A2.5 2.5 0 0 0 7.5 20h9a2.5 2.5 0 0 0 2.5-2.5v-4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Add photos</span></button></div></div>
          </div>
          <input id="imageFile" class="image-file-input" type="file" accept="image/jpeg,image/png,image/webp" multiple/>
          <div id="imageSources" class="image-sources" aria-hidden="true"><div class="image-sources-head"><span id="imageSourcesCount">0 selected</span><small>Up to 4 photos</small></div><div id="imageSourcesGrid" class="image-sources-grid"></div></div>
          <button id="generateImageButton" class="image-generate" data-action="generate-image" type="button"><span id="generateImageLabel">Generate image</span><svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
          <div id="imageResult" class="image-result" aria-hidden="true"><div class="image-result-frame"><img id="imageResultPreview" alt="Generated image"/><div class="image-result-shine" aria-hidden="true"></div></div><div class="image-result-actions"><button data-action="share-image" type="button"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 15.5V4m0 0L7.8 8.2M12 4l4.2 4.2M5.5 13.5v4A2.5 2.5 0 0 0 8 20h8a2.5 2.5 0 0 0 2.5-2.5v-4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Share</span></button><button data-action="download-image" type="button"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M12 4v11m0 0 4-4m-4 4-4-4M5 19h14" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg><span>Save</span></button></div></div>
          <section id="imageHistorySection" class="image-history-section" aria-hidden="true"><div class="image-history-head"><span>CREATIONS</span><small id="imageHistoryCount">0</small></div><div id="imageHistoryGrid" class="image-history-grid"></div></section>
        </section>
        <div class="history-sheet" id="historySheet" aria-hidden="true"><button class="history-backdrop" data-action="close-history" type="button" aria-label="Close history"></button><section class="history-card" role="dialog" aria-modal="true" aria-label="Voice history"><label class="history-search" for="historySearch"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.3" stroke="currentColor" stroke-width="1.9"/><path d="m15.5 15.5 4 4" stroke="currentColor" stroke-width="1.9" stroke-linecap="round"/></svg><input id="historySearch" type="search" autocomplete="off" placeholder="Search your voice history..."/></label><div id="historyList" class="history-list"><div class="history-loading"><span></span><span></span><span></span></div></div></section></div>
        <div class="voice-settings-sheet" id="voiceSettingsSheet" aria-hidden="true"><button class="voice-settings-backdrop" data-action="close-voice-settings" type="button" aria-label="Close voice settings"></button><section class="voice-settings-card" role="dialog" aria-modal="true" aria-label="Voice settings"><div class="sheet-handle" aria-hidden="true"></div><div class="settings-head"><div><span class="settings-eyebrow">VOICE CONTROL</span><h2>Sound settings</h2></div><button class="settings-reset" data-action="reset-voice-settings" type="button">Reset</button></div><div class="settings-panel"><div class="stability-title">Stability</div><div class="stability-labels"><span>Creative</span><span>Robust</span></div><input id="stabilitySlider" class="stability-slider" type="range" min="0" max="100" step="1" value="50" aria-label="Stability from creative to robust"/><p class="model-note">Lower values feel more expressive · Higher values sound more consistent</p></div><button id="saveVoiceSettings" class="settings-save" data-action="save-voice-settings" type="button"><span>Save settings</span></button></section></div>
        <div class="limit-sheet" id="ttsLimitSheet" aria-hidden="true"><button class="limit-backdrop" data-action="close-char-limit" type="button" aria-label="Close"></button><div class="limit-card" id="ttsWarningCard"><div class="limit-icon"><span>!</span></div><h3 id="ttsWarningTitle">Character limit</h3><p id="ttsWarningText">You can’t convert more than 1000 characters</p><button class="limit-close" id="ttsWarningClose" data-action="close-char-limit" type="button">Got it</button></div></div>
      </div>
    </section>
  </main>
  <div id="toast" class="toast" role="status"></div>
  <script src="https://telegram.org/js/telegram-web-app.js"></script>
  <script type="module" src="/mini-app/app.js?v=20260720-23"></script>
</body>
</html>`;
