export const DEMO_TEXTS = {
  Liam: {
    en: "A calm voice can make a short story feel close and real",
    ru: "Спокойный голос делает короткий рассказ ближе и живее",
    de: "Eine ruhige Stimme macht kurze Geschichten nah und echt",
    fa: "صدایی آرام و واضح، مناسب برای روایت‌های کوتاه و شنیدنی",
    tr: "Sakin bir ses kısa hikayeleri daha yakın ve gerçek yapar",
    ar: "الصوت الهادئ يجعل القصة القصيرة أقرب وأكثر حياة",
    zh: "平静的声音能让短故事更真实亲近",
    ja: "落ち着いた声は短い物語を身近でリアルにします",
    es: "Una voz tranquila hace que una historia breve se sienta real",
    hi: "एक शांत आवाज़ छोटी कहानी को करीब और सजीव बना देती है",
  },
  Noah: {
    en: "Simple words can feel alive when they are spoken naturally",
    ru: "Простые слова оживают, когда звучат естественно",
    de: "Einfache Worte wirken lebendig, wenn sie natürlich klingen",
    fa: "کلمات ساده می‌توانند با صدایی طبیعی حس واقعی پیدا کنند",
    tr: "Basit kelimeler doğal okununca canlı bir his verir",
    ar: "الكلمات البسيطة تبدو حية عندما تُقال بصوت طبيعي",
    zh: "简单文字用自然声音读出会更有生命力",
    ja: "シンプルな言葉も自然な声で生き生きと伝わります",
    es: "Las palabras simples cobran vida con una voz natural",
    hi: "सरल शब्द भी प्राकृतिक आवाज़ में जीवंत लगते हैं",
  },
  Ava: {
    en: "A soft clear tone can turn written lines into warm speech",
    ru: "Мягкий чистый тон превращает строки в теплую речь",
    de: "Ein sanfter klarer Ton verwandelt Zeilen in warme Sprache",
    fa: "نوشته‌های شما با لحنی نرم، روشن و دلنشین شنیده می‌شوند",
    tr: "Yumuşak ve net bir ton yazıları sıcak bir sese çevirir",
    ar: "نبرة ناعمة وواضحة تحول السطور إلى حديث دافئ",
    zh: "柔和清晰的语调能把文字变成温暖的话语",
    ja: "やわらかく明瞭な声が文章を温かな音声に変えます",
    es: "Un tono suave y claro convierte líneas escritas en voz cálida",
    hi: "नरम और साफ़ लहजा लिखे शब्दों को गर्म आवाज़ देता है",
  },
  Nora: {
    en: "Even one short sentence can sound powerful with the right voice",
    ru: "Даже короткая фраза звучит сильнее с правильным голосом",
    de: "Schon ein kurzer Satz kann mit der richtigen Stimme stark wirken",
    fa: "یک جمله کوتاه هم می‌تواند با صدای درست، تاثیرگذار باشد",
    tr: "Kısa bir cümle bile doğru sesle etkileyici olabilir",
    ar: "حتى الجملة القصيرة تصبح مؤثرة بالصوت المناسب",
    zh: "一句短话也能因合适的声音而更有力量",
    ja: "短い一文でも声が合えば強く印象に残ります",
    es: "Una frase corta puede impactar con la voz adecuada",
    hi: "सही आवाज़ से छोटी पंक्ति भी असरदार बन जाती है",
  },
  Alex: {
    en: "Text to speech should be fast clear and truly natural",
    ru: "Озвучивание текста должно быть быстрым ясным и естественным",
    de: "Text zu Sprache sollte schnell klar und wirklich natürlich sein",
    fa: "تبدیل متن به گفتار باید سریع، شفاف و کاملاً طبیعی باشد",
    tr: "Metinden sese dönüşüm hızlı net ve doğal olmalıdır",
    ar: "تحويل النص إلى صوت يجب أن يكون سريعاً وواضحاً وطبيعياً",
    zh: "文字转语音应该快速清晰并且自然",
    ja: "テキスト読み上げは速く明瞭で自然であるべきです",
    es: "Convertir texto en voz debe ser rápido claro y natural",
    hi: "टेक्स्ट से आवाज़ बनना तेज़ साफ़ और प्राकृतिक होना चाहिए",
  },
  Ella: {
    en: "A warm flowing voice helps every sentence sound more beautiful",
    ru: "Теплый плавный голос делает каждую фразу красивее",
    de: "Eine warme fließende Stimme lässt jeden Satz schöner klingen",
    fa: "صدایی گرم و روان برای جمله‌هایی که باید زیبا شنیده شوند",
    tr: "Sıcak ve akıcı bir ses her cümleyi daha güzel duyurur",
    ar: "صوت دافئ وسلس يجعل كل جملة أجمل عند الاستماع",
    zh: "温暖流畅的声音让每句话更动听",
    ja: "温かく流れる声がすべての文を美しく響かせます",
    es: "Una voz cálida y fluida hace que cada frase suene mejor",
    hi: "गर्म और सहज आवाज़ हर वाक्य को अधिक सुंदर बनाती है",
  },
  Chloe: {
    en: "Any written line can become clear lively and easy to understand",
    ru: "Любая строка может стать ясной живой и понятной",
    de: "Jede geschriebene Zeile kann klar lebendig und verständlich werden",
    fa: "هر نوشته می‌تواند به گفتاری زنده، تمیز و قابل فهم تبدیل شود",
    tr: "Her yazı canlı temiz ve anlaşılır bir konuşmaya dönüşebilir",
    ar: "كل نص يمكن أن يتحول إلى كلام واضح وحيوي وسهل الفهم",
    zh: "每段文字都能变得清楚生动且容易理解",
    ja: "どんな文章も明瞭で生き生きとわかりやすくなります",
    es: "Cualquier texto puede volverse claro vivo y fácil de entender",
    hi: "हर लिखा वाक्य साफ़ जीवंत और समझने योग्य बन सकता है",
  },
  Alexandra: {
    en: "A professional voice makes simple sentences more engaging",
    ru: "Профессиональный голос делает простые фразы интереснее",
    de: "Eine professionelle Stimme macht einfache Sätze spannender",
    fa: "صدای حرفه‌ای، جمله‌های ساده را جذاب‌تر و شنیدنی‌تر می‌کند",
    tr: "Profesyonel bir ses basit cümleleri daha ilgi çekici yapar",
    ar: "الصوت الاحترافي يجعل الجمل البسيطة أكثر جاذبية",
    zh: "专业声音能让简单句子更有吸引力",
    ja: "プロらしい声はシンプルな文をより魅力的にします",
    es: "Una voz profesional vuelve más atractivas las frases simples",
    hi: "पेशेवर आवाज़ सरल वाक्यों को अधिक आकर्षक बनाती है",
  },
  Laura: {
    en: "Short texts feel better when the voice is clean and bright",
    ru: "Короткие тексты звучат лучше с чистым и светлым голосом",
    de: "Kurze Texte wirken besser mit einer klaren hellen Stimme",
    fa: "متن‌های کوتاه با صدایی شفاف، حس بهتری منتقل می‌کنند",
    tr: "Kısa metinler temiz ve parlak bir sesle daha iyi hissedilir",
    ar: "النصوص القصيرة تبدو أفضل بصوت صاف ومشرق",
    zh: "短文本配上清晰明亮的声音会更好",
    ja: "短い文章は明るく澄んだ声でより良く伝わります",
    es: "Los textos breves se sienten mejor con una voz limpia y clara",
    hi: "छोटे पाठ साफ़ और उजली आवाज़ में बेहतर लगते हैं",
  },
  Maxon: {
    en: "A strong voice can give every sentence more character",
    ru: "Сильный голос придает каждой фразе больше характера",
    de: "Eine starke Stimme gibt jedem Satz mehr Charakter",
    fa: "یک صدای قدرتمند می‌تواند به هر جمله شخصیت بیشتری بدهد",
    tr: "Güçlü bir ses her cümleye daha fazla karakter katar",
    ar: "الصوت القوي يمنح كل جملة شخصية أوضح",
    zh: "有力量的声音能让每句话更有个性",
    ja: "力強い声はどんな文にも個性を与えます",
    es: "Una voz fuerte puede dar más carácter a cada frase",
    hi: "मजबूत आवाज़ हर वाक्य को अधिक व्यक्तित्व देती है",
  },
  Jessica: {
    en: "A smooth natural voice can make written words feel friendly",
    ru: "Плавный естественный голос делает текст более дружелюбным",
    de: "Eine sanfte natürliche Stimme lässt Worte freundlicher wirken",
    fa: "گفتاری نرم و طبیعی، نوشته‌ها را صمیمی‌تر نشان می‌دهد",
    tr: "Pürüzsüz doğal bir ses yazıları daha samimi gösterir",
    ar: "الصوت الناعم والطبيعي يجعل الكلمات أكثر قرباً",
    zh: "流畅自然的声音让文字更亲切",
    ja: "なめらかで自然な声は文章を親しみやすくします",
    es: "Una voz suave y natural hace que las palabras sean cercanas",
    hi: "मुलायम प्राकृतिक आवाज़ लिखे शब्दों को अपनापन देती है",
  },
  Austin: {
    en: "For lessons stories or intros a clear voice always matters",
    ru: "Для уроков историй и вступлений ясный голос всегда важен",
    de: "Für Lektionen Geschichten oder Intros ist klare Stimme wichtig",
    fa: "برای روایت، آموزش یا معرفی، صدای واضح همیشه مهم است",
    tr: "Anlatım ders ya da tanıtım için net ses her zaman önemlidir",
    ar: "في السرد أو التعليم أو التعريف يبقى الصوت الواضح مهماً",
    zh: "讲解故事或介绍都需要清晰的声音",
    ja: "解説や物語や紹介には明瞭な声が欠かせません",
    es: "Para clases relatos o presentaciones una voz clara importa",
    hi: "कहानी पाठ या परिचय में साफ़ आवाज़ हमेशा महत्वपूर्ण होती है",
  },
  priyanka: {
    en: "Words become more memorable when they are spoken with care",
    ru: "Слова лучше запоминаются когда звучат с правильным тоном",
    de: "Worte bleiben besser hängen wenn sie sorgfältig gesprochen werden",
    fa: "جمله‌ها وقتی با لحن درست خوانده شوند، ماندگارتر می‌شوند",
    tr: "Sözler doğru tonla okunduğunda daha kalıcı olur",
    ar: "الكلمات تصبح أرسخ عندما تُقرأ بنبرة مناسبة",
    zh: "用心读出的文字更容易被记住",
    ja: "丁寧に読まれた言葉はより記憶に残ります",
    es: "Las palabras se recuerdan más cuando se dicen con cuidado",
    hi: "ध्यान से बोली गई बातें अधिक यादगार बन जाती हैं",
  },
  horatius: {
    en: "A deep steady voice can make a message feel serious and unique",
    ru: "Глубокий ровный голос делает сообщение серьезным и особенным",
    de: "Eine tiefe ruhige Stimme lässt eine Botschaft besonders wirken",
    fa: "صدایی عمیق و آرام می‌تواند متن را جدی‌تر و خاص‌تر کند",
    tr: "Derin ve sakin bir ses metni daha ciddi ve özel yapar",
    ar: "الصوت العميق والهادئ يجعل النص أكثر جدية وتميزاً",
    zh: "低沉稳定的声音让内容更严肃独特",
    ja: "深く落ち着いた声は文章を重く特別に感じさせます",
    es: "Una voz profunda y serena hace el mensaje más especial",
    hi: "गहरी स्थिर आवाज़ संदेश को गंभीर और खास बनाती है",
  },
  anika: {
    en: "Simple writing can sound elegant when the voice flows naturally",
    ru: "Простой текст звучит изящно когда голос течет естественно",
    de: "Einfacher Text klingt elegant wenn die Stimme natürlich fließt",
    fa: "نوشته‌های ساده با صدایی روان، زیباتر و طبیعی‌تر شنیده می‌شوند",
    tr: "Basit yazılar doğal akan bir sesle daha zarif duyulur",
    ar: "الكتابة البسيطة تبدو أجمل عندما ينساب الصوت طبيعياً",
    zh: "自然流畅的声音让简单文字更优雅",
    ja: "自然に流れる声でシンプルな文章も上品に響きます",
    es: "Un texto simple suena elegante con una voz natural y fluida",
    hi: "सरल लेखन प्राकृतिक प्रवाह वाली आवाज़ में सुंदर लगता है",
  },
  brock: {
    en: "A firm clear tone sends your message in a direct way",
    ru: "Уверенный ясный тон передает сообщение прямо и четко",
    de: "Ein fester klarer Ton bringt deine Botschaft direkt rüber",
    fa: "یک لحن محکم و واضح، پیام شما را مستقیم‌تر منتقل می‌کند",
    tr: "Net ve güçlü bir ton mesajınızı daha doğrudan iletir",
    ar: "النبرة الواضحة والثابتة توصل رسالتك بشكل مباشر",
    zh: "坚定清晰的语气能直接传达信息",
    ja: "はっきりした力強い声はメッセージをまっすぐ届けます",
    es: "Un tono firme y claro transmite tu mensaje de forma directa",
    hi: "मजबूत साफ़ लहजा संदेश को सीधे पहुँचाता है",
  },
  Xavier: {
    en: "Natural speech helps text feel more alive and believable",
    ru: "Естественная речь делает текст живее и убедительнее",
    de: "Natürliche Sprache lässt Text lebendiger und echter wirken",
    fa: "گفتار طبیعی باعث می‌شود متن، زنده‌تر و واقعی‌تر احساس شود",
    tr: "Doğal konuşma metni daha canlı ve gerçek hissettirir",
    ar: "الكلام الطبيعي يجعل النص أكثر حياة وواقعية",
    zh: "自然语音让文字更生动可信",
    ja: "自然な話し方は文章をより生き生きと感じさせます",
    es: "El habla natural hace que el texto se sienta vivo y real",
    hi: "प्राकृतिक बोलचाल पाठ को अधिक जीवंत और असली बनाती है",
  },
  Lucas: {
    en: "A balanced clear voice turns writing into smooth speech",
    ru: "Ровный ясный голос превращает текст в плавную речь",
    de: "Eine klare ausgewogene Stimme macht Text zu flüssiger Sprache",
    fa: "صدایی شفاف و متعادل برای تبدیل نوشته‌ها به گفتاری روان",
    tr: "Dengeli ve net bir ses yazıyı akıcı konuşmaya çevirir",
    ar: "صوت واضح ومتوازن يحول الكتابة إلى حديث سلس",
    zh: "均衡清晰的声音把文字变成流畅语音",
    ja: "明瞭で整った声が文章をなめらかな音声に変えます",
    es: "Una voz clara y equilibrada convierte texto en habla fluida",
    hi: "संतुलित साफ़ आवाज़ लिखे पाठ को सहज बोलचाल बनाती है",
  },
};

export function getDemoText(language, voice) {
  const lang = language || "en";
  return DEMO_TEXTS[voice]?.[lang] || DEMO_TEXTS[voice]?.en || DEMO_TEXTS.Nora[lang] || DEMO_TEXTS.Nora.en;
}
