export const DEMO_TEXTS = {
  Liam: {
    en: "A calm voice can make a short story feel close and real",
    ru: "Спокойный голос делает короткий рассказ ближе и живее",
    de: "Eine ruhige Stimme macht kurze Geschichten nah und echt",
    fa: "یه صدای آروم می‌تونه یه متن کوتاه رو خیلی شنیدنی کنه",
    tr: "Sakin bir ses kısa hikayeleri daha yakın ve gerçek yapar",
    ar: "الصوت الهادئ يجعل القصة القصيرة أقرب وأكثر حياة",
    zh: "平静的声音能让短故事更真实亲近",
    ja: "落ち着いた声は短い物語を身近でリアルにします",
    es: "Una voz tranquila hace que una historia breve se sienta real",
    hi: "एक शांत आवाज़ छोटी कहानी को करीब और सजीव बना देती है",
  },
  Noah: {
    en: "Simple words can feel alive when they are spoken naturally",
    ru: "Простые слова оживают, когда звучат естественно",
    de: "Einfache Worte wirken lebendig, wenn sie natürlich klingen",
    fa: "گاهی چند کلمه ساده با صدای طبیعی خیلی بهتر شنیده می‌شن",
    tr: "Basit kelimeler doğal okununca canlı bir his verir",
    ar: "الكلمات البسيطة تبدو حية عندما تُقال بصوت طبيعي",
    zh: "简单文字用自然声音读出会更有生命力",
    ja: "シンプルな言葉も自然な声で生き生きと伝わります",
    es: "Las palabras simples cobran vida con una voz natural",
    hi: "सरल शब्द भी प्राकृतिक आवाज़ में जीवंत लगते हैं",
  },
  Ava: {
    en: "A soft clear tone can turn written lines into warm speech",
    ru: "Мягкий чистый тон превращает строки в теплую речь",
    de: "Ein sanfter klarer Ton verwandelt Zeilen in warme Sprache",
    fa: "متن‌هات با یه لحن نرم و روشن، قشنگ‌تر به گوش می‌رسن",
    tr: "Yumuşak ve net bir ton yazıları sıcak bir sese çevirir",
    ar: "نبرة ناعمة وواضحة تحول السطور إلى حديث دافئ",
    zh: "柔和清晰的语调能把文字变成温暖的话语",
    ja: "やわらかく明瞭な声が文章を温かな音声に変えます",
    es: "Un tono suave y claro convierte líneas escritas en voz cálida",
    hi: "नरम और साफ़ लहजा लिखे शब्दों को गर्म आवाज़ देता है",
  },
  Nora: {
    en: "Even one short sentence can sound powerful with the right voice",
    ru: "Даже короткая фраза звучит сильнее с правильным голосом",
    de: "Schon ein kurzer Satz kann mit der richtigen Stimme stark wirken",
    fa: "یه جمله کوتاه هم با صدای خوب می‌تونه حسابی اثر بذاره",
    tr: "Kısa bir cümle bile doğru sesle etkileyici olabilir",
    ar: "حتى الجملة القصيرة تصبح مؤثرة بالصوت المناسب",
    zh: "一句短话也能因合适的声音而更有力量",
    ja: "短い一文でも声が合えば強く印象に残ります",
    es: "Una frase corta puede impactar con la voz adecuada",
    hi: "सही आवाज़ से छोटी पंक्ति भी असरदार बन जाती है",
  },
  Alex: {
    en: "Text to speech should be fast clear and truly natural",
    ru: "Озвучивание текста должно быть быстрым ясным и естественным",
    de: "Text zu Sprache sollte schnell klar und wirklich natürlich sein",
    fa: "تبدیل متن به صدا باید سریع، واضح و طبیعی باشه",
    tr: "Metinden sese dönüşüm hızlı net ve doğal olmalıdır",
    ar: "تحويل النص إلى صوت يجب أن يكون سريعاً وواضحاً وطبيعياً",
    zh: "文字转语音应该快速清晰并且自然",
    ja: "テキスト読み上げは速く明瞭で自然であるべきです",
    es: "Convertir texto en voz debe ser rápido claro y natural",
    hi: "टेक्स्ट से आवाज़ बनना तेज़ साफ़ और प्राकृतिक होना चाहिए",
  },
  Ella: {
    en: "A warm flowing voice helps every sentence sound more beautiful",
    ru: "Теплый плавный голос делает каждую фразу красивее",
    de: "Eine warme fließende Stimme lässt jeden Satz schöner klingen",
    fa: "یه صدای گرم و روان می‌تونه هر جمله‌ای رو قشنگ‌تر کنه",
    tr: "Sıcak ve akıcı bir ses her cümleyi daha güzel duyurur",
    ar: "صوت دافئ وسلس يجعل كل جملة أجمل عند الاستماع",
    zh: "温暖流畅的声音让每句话更动听",
    ja: "温かく流れる声がすべての文を美しく響かせます",
    es: "Una voz cálida y fluida hace que cada frase suene mejor",
    hi: "गर्म और सहज आवाज़ हर वाक्य को अधिक सुंदर बनाती है",
  },
  Chloe: {
    en: "Any written line can become clear lively and easy to understand",
    ru: "Любая строка может стать ясной живой и понятной",
    de: "Jede geschriebene Zeile kann klar lebendig und verständlich werden",
    fa: "هر نوشته‌ای می‌تونه به یه صدای زنده و قابل فهم تبدیل بشه",
    tr: "Her yazı canlı temiz ve anlaşılır bir konuşmaya dönüşebilir",
    ar: "كل نص يمكن أن يتحول إلى كلام واضح وحيوي وسهل الفهم",
    zh: "每段文字都能变得清楚生动且容易理解",
    ja: "どんな文章も明瞭で生き生きとわかりやすくなります",
    es: "Cualquier texto puede volverse claro vivo y fácil de entender",
    hi: "हर लिखा वाक्य साफ़ जीवंत और समझने योग्य बन सकता है",
  },
  Alexandra: {
    en: "A professional voice makes simple sentences more engaging",
    ru: "Профессиональный голос делает простые фразы интереснее",
    de: "Eine professionelle Stimme macht einfache Sätze spannender",
    fa: "با یه صدای حرفه‌ای، حتی جمله‌های ساده هم جذاب‌تر می‌شن",
    tr: "Profesyonel bir ses basit cümleleri daha ilgi çekici yapar",
    ar: "الصوت الاحترافي يجعل الجمل البسيطة أكثر جاذبية",
    zh: "专业声音能让简单句子更有吸引力",
    ja: "プロらしい声はシンプルな文をより魅力的にします",
    es: "Una voz profesional vuelve más atractivas las frases simples",
    hi: "पेशेवर आवाज़ सरल वाक्यों को अधिक आकर्षक बनाती है",
  },
  Laura: {
    en: "Short texts feel better when the voice is clean and bright",
    ru: "Короткие тексты звучат лучше с чистым и светлым голосом",
    de: "Kurze Texte wirken besser mit einer klaren hellen Stimme",
    fa: "متن‌های کوتاه با صدای شفاف خیلی بهتر حس می‌شن",
    tr: "Kısa metinler temiz ve parlak bir sesle daha iyi hissedilir",
    ar: "النصوص القصيرة تبدو أفضل بصوت صاف ومشرق",
    zh: "短文本配上清晰明亮的声音会更好",
    ja: "短い文章は明るく澄んだ声でより良く伝わります",
    es: "Los textos breves se sienten mejor con una voz limpia y clara",
    hi: "छोटे पाठ साफ़ और उजली आवाज़ में बेहतर लगते हैं",
  },
  Maxon: {
    en: "A strong voice can give every sentence more character",
    ru: "Сильный голос придает каждой фразе больше характера",
    de: "Eine starke Stimme gibt jedem Satz mehr Charakter",
    fa: "یه صدای قوی می‌تونه به هر جمله شخصیت بیشتری بده",
    tr: "Güçlü bir ses her cümleye daha fazla karakter katar",
    ar: "الصوت القوي يمنح كل جملة شخصية أوضح",
    zh: "有力量的声音能让每句话更有个性",
    ja: "力強い声はどんな文にも個性を与えます",
    es: "Una voz fuerte puede dar más carácter a cada frase",
    hi: "मजबूत आवाज़ हर वाक्य को अधिक व्यक्तित्व देती है",
  },
  Jessica: {
    en: "A smooth natural voice can make written words feel friendly",
    ru: "Плавный естественный голос делает текст более дружелюбным",
    de: "Eine sanfte natürliche Stimme lässt Worte freundlicher wirken",
    fa: "یه صدای نرم و طبیعی، نوشته‌ها رو صمیمی‌تر می‌کنه",
    tr: "Pürüzsüz doğal bir ses yazıları daha samimi gösterir",
    ar: "الصوت الناعم والطبيعي يجعل الكلمات أكثر قرباً",
    zh: "流畅自然的声音让文字更亲切",
    ja: "なめらかで自然な声は文章を親しみやすくします",
    es: "Una voz suave y natural hace que las palabras sean cercanas",
    hi: "मुलायम प्राकृतिक आवाज़ लिखे शब्दों को अपनापन देती है",
  },
  Austin: {
    en: "For lessons stories or intros a clear voice always matters",
    ru: "Для уроков историй и вступлений ясный голос всегда важен",
    de: "Für Lektionen Geschichten oder Intros ist klare Stimme wichtig",
    fa: "برای آموزش، معرفی یا روایت، صدای واضح خیلی مهمه",
    tr: "Anlatım ders ya da tanıtım için net ses her zaman önemlidir",
    ar: "في السرد أو التعليم أو التعريف يبقى الصوت الواضح مهماً",
    zh: "讲解故事或介绍都需要清晰的声音",
    ja: "解説や物語や紹介には明瞭な声が欠かせません",
    es: "Para clases relatos o presentaciones una voz clara importa",
    hi: "कहानी पाठ या परिचय में साफ़ आवाज़ हमेशा महत्वपूर्ण होती है",
  },
  priyanka: {
    en: "Words become more memorable when they are spoken with care",
    ru: "Слова лучше запоминаются когда звучат с правильным тоном",
    de: "Worte bleiben besser hängen wenn sie sorgfältig gesprochen werden",
    fa: "وقتی جمله‌ها با لحن درست خونده بشن، بیشتر تو ذهن می‌مونن",
    tr: "Sözler doğru tonla okunduğunda daha kalıcı olur",
    ar: "الكلمات تصبح أرسخ عندما تُقرأ بنبرة مناسبة",
    zh: "用心读出的文字更容易被记住",
    ja: "丁寧に読まれた言葉はより記憶に残ります",
    es: "Las palabras se recuerdan más cuando se dicen con cuidado",
    hi: "ध्यान से बोली गई बातें अधिक यादगार बन जाती हैं",
  },
  horatius: {
    en: "A deep steady voice can make a message feel serious and unique",
    ru: "Глубокий ровный голос делает сообщение серьезным и особенным",
    de: "Eine tiefe ruhige Stimme lässt eine Botschaft besonders wirken",
    fa: "یه صدای عمیق و آروم می‌تونه متن رو خاص‌تر کنه",
    tr: "Derin ve sakin bir ses metni daha ciddi ve özel yapar",
    ar: "الصوت العميق والهادئ يجعل النص أكثر جدية وتميزاً",
    zh: "低沉稳定的声音让内容更严肃独特",
    ja: "深く落ち着いた声は文章を重く特別に感じさせます",
    es: "Una voz profunda y serena hace el mensaje más especial",
    hi: "गहरी स्थिर आवाज़ संदेश को गंभीर और खास बनाती है",
  },
  Nova: {
    en: "Simple writing can sound elegant when the voice flows naturally",
    ru: "Простой текст звучит изящно когда голос течет естественно",
    de: "Einfacher Text klingt elegant wenn die Stimme natürlich fließt",
    fa: "نوشته‌های ساده با صدای روان، خیلی طبیعی‌تر شنیده می‌شن",
    tr: "Basit yazılar doğal akan bir sesle daha zarif duyulur",
    ar: "الكتابة البسيطة تبدو أجمل عندما ينساب الصوت طبيعياً",
    zh: "自然流畅的声音让简单文字更优雅",
    ja: "自然に流れる声でシンプルな文章も上品に響きます",
    es: "Un texto simple suena elegante con una voz natural y fluida",
    hi: "सरल लेखन प्राकृतिक प्रवाह वाली आवाज़ में सुंदर लगता है",
  },
  James: {
    en: "A firm clear tone sends your message in a direct way",
    ru: "Уверенный ясный тон передает сообщение прямо и четко",
    de: "Ein fester klarer Ton bringt deine Botschaft direkt rüber",
    fa: "یه لحن محکم و واضح، پیام رو مستقیم‌تر منتقل می‌کنه",
    tr: "Net ve güçlü bir ton mesajınızı daha doğrudan iletir",
    ar: "النبرة الواضحة والثابتة توصل رسالتك بشكل مباشر",
    zh: "坚定清晰的语气能直接传达信息",
    ja: "はっきりした力強い声はメッセージをまっすぐ届けます",
    es: "Un tono firme y claro transmite tu mensaje de forma directa",
    hi: "मजबूत साफ़ लहजा संदेश को सीधे पहुँचाता है",
  },
  Xavier: {
    en: "Natural speech helps text feel more alive and believable",
    ru: "Естественная речь делает текст живее и убедительнее",
    de: "Natürliche Sprache lässt Text lebendiger und echter wirken",
    fa: "صدای طبیعی باعث می‌شه متن زنده‌تر و واقعی‌تر حس بشه",
    tr: "Doğal konuşma metni daha canlı ve gerçek hissettirir",
    ar: "الكلام الطبيعي يجعل النص أكثر حياة وواقعية",
    zh: "自然语音让文字更生动可信",
    ja: "自然な話し方は文章をより生き生きと感じさせます",
    es: "El habla natural hace que el texto se sienta vivo y real",
    hi: "प्राकृतिक बोलचाल पाठ को अधिक जीवंत और असली बनाती है",
  },
  Lucas: {
    en: "A balanced clear voice turns writing into smooth speech",
    ru: "Ровный ясный голос превращает текст в плавную речь",
    de: "Eine klare ausgewogene Stimme macht Text zu flüssiger Sprache",
    fa: "یه صدای شفاف و متعادل، متن رو به گفتاری روان تبدیل می‌کنه",
    tr: "Dengeli ve net bir ses yazıyı akıcı konuşmaya çevirir",
    ar: "صوت واضح ومتوازن يحول الكتابة إلى حديث سلس",
    zh: "均衡清晰的声音把文字变成流畅语音",
    ja: "明瞭で整った声が文章をなめらかな音声に変えます",
    es: "Una voz clara y equilibrada convierte texto en habla fluida",
    hi: "संतुलित साफ़ आवाज़ लिखे पाठ को सहज बोलचाल बनाती है",
  },
  Lana: {
    en: "Stay a little longer; this voice turns a quiet message into a warm memory",
    ru: "Останься чуть дольше; этот голос превращает тихие слова в теплое воспоминание",
    de: "Bleib einen Moment länger; diese Stimme macht leise Worte zu einer warmen Erinnerung",
    fa: "یه لحظه بیشتر گوش کن؛ این صدا حرفای آروم رو به یه خاطره گرم تبدیل می‌کنه",
    tr: "Biraz daha dinle; bu ses sakin sözleri sıcak bir anıya çevirir",
    ar: "ابقَ قليلاً؛ هذا الصوت يحول الكلام الهادئ إلى ذكرى دافئة",
    zh: "再多听一会儿；这个声音把安静的话变成温暖记忆",
    ja: "もう少し聴いていてください。この声は静かな言葉を温かな記憶に変えます",
    es: "Quédate un poco más; esta voz convierte un mensaje suave en un recuerdo cálido",
    hi: "थोड़ा और ठहरिए; यह आवाज़ शांत संदेश को गर्म याद बना देती है",
  },
  Amanda: {
    en: "Your story deserves a voice that feels close, honest, and easy to trust",
    ru: "Твоя история заслуживает голос, который звучит близко, честно и надежно",
    de: "Deine Geschichte verdient eine Stimme, die nah, ehrlich und vertrauensvoll klingt",
    fa: "داستان تو لایق صداییه که نزدیک، صادق و قابل اعتماد حس بشه",
    tr: "Hikayen yakın, dürüst ve güven veren bir sesi hak ediyor",
    ar: "قصتك تستحق صوتاً قريباً وصادقاً وسهل الثقة",
    zh: "你的故事值得一个亲近、真诚、值得信任的声音",
    ja: "あなたの物語には、近くて誠実で信頼できる声が似合います",
    es: "Tu historia merece una voz cercana, honesta y fácil de creer",
    hi: "आपकी कहानी ऐसी आवाज़ चाहती है जो करीब, सच्ची और भरोसेमंद लगे",
  },
  Scarlett: {
    en: "One confident sentence can pull people in and make them want the next line",
    ru: "Одна уверенная фраза может увлечь людей и заставить ждать следующую строку",
    de: "Ein selbstbewusster Satz kann Menschen fesseln und Lust auf die nächste Zeile machen",
    fa: "یه جمله بااعتمادبه‌نفس می‌تونه مخاطب رو جذب کنه و منتظر جمله بعدی نگه داره",
    tr: "Kendinden emin bir cümle insanı içine çeker ve sonraki satırı merak ettirir",
    ar: "جملة واثقة واحدة قد تجذب المستمع وتجعله ينتظر السطر التالي",
    zh: "一句自信的话就能吸引人，让人想听下一句",
    ja: "自信のある一文は人を引き込み、次の言葉を待たせます",
    es: "Una frase segura puede atraer a todos y hacer que quieran la siguiente línea",
    hi: "आत्मविश्वास वाली एक पंक्ति लोगों को खींचती है और अगली पंक्ति सुनना चाहती है",
  },
  Aurora: {
    en: "If your heart had a sunrise, it might sound gentle, bright, and impossible to skip",
    ru: "Если бы у сердца был рассвет, он звучал бы нежно, светло и незабываемо",
    de: "Wenn dein Herz einen Sonnenaufgang hätte, klänge er sanft, hell und unwiderstehlich",
    fa: "اگه قلبت طلوع داشت، احتمالاً همین‌قدر لطیف، روشن و شنیدنی صدا می‌داد",
    tr: "Kalbinin bir gün doğumu olsaydı nazik, parlak ve vazgeçilmez duyulurdu",
    ar: "لو كان لقلبك شروق، لكان صوته لطيفاً ومشرقاً ولا يُفوَّت",
    zh: "如果心里有日出，它也许会这样温柔、明亮、让人舍不得跳过",
    ja: "心に朝日があるなら、きっと優しく明るく、聴き逃せない音になります",
    es: "Si tu corazón tuviera un amanecer, sonaría suave, luminoso e imposible de saltar",
    hi: "अगर दिल की सुबह की आवाज़ होती, तो वह नरम, उजली और सुनने लायक होती",
  },
  Allison: {
    en: "Let the first word feel personal, then the whole message becomes hard to ignore",
    ru: "Пусть первое слово прозвучит лично, и все сообщение станет трудно пропустить",
    de: "Wenn das erste Wort persönlich klingt, wird die ganze Botschaft schwer zu überhören",
    fa: "کافیه اولین کلمه شخصی و نزدیک شنیده بشه؛ بعدش کل پیام سخت فراموش می‌شه",
    tr: "İlk kelime kişisel hissetsin; sonra tüm mesajı görmezden gelmek zorlaşır",
    ar: "اجعل الكلمة الأولى شخصية، وسيصبح تجاهل الرسالة كلها صعباً",
    zh: "让第一个字听起来像对他说，整段信息就很难被忽略",
    ja: "最初の一言が自分に向けられたように響くと、全体が忘れにくくなります",
    es: "Haz que la primera palabra se sienta personal y todo el mensaje será difícil de ignorar",
    hi: "पहला शब्द निजी लगे, फिर पूरा संदेश नज़रअंदाज़ करना मुश्किल हो जाता है",
  },
  Mason: {
    en: "A deep voice can make even a simple promise feel strong, safe, and unforgettable",
    ru: "Глубокий голос делает даже простое обещание сильным, спокойным и незабываемым",
    de: "Eine tiefe Stimme lässt selbst ein schlichtes Versprechen stark, sicher und unvergesslich wirken",
    fa: "یه صدای عمیق حتی یه قول ساده رو محکم، امن و فراموش‌نشدنی می‌کنه",
    tr: "Derin bir ses basit bir sözü bile güçlü, güvenli ve unutulmaz hissettirir",
    ar: "الصوت العميق يجعل الوعد البسيط قوياً وآمناً ولا يُنسى",
    zh: "低沉的声音让简单承诺也显得坚定、安全、难忘",
    ja: "深い声は、素朴な約束さえ強く安心できて忘れられないものにします",
    es: "Una voz profunda hace que una promesa simple se sienta fuerte, segura e inolvidable",
    hi: "गहरी आवाज़ साधारण वादे को भी मजबूत, सुरक्षित और यादगार बना देती है",
  },

  Aria: {
    en: "[warmly] Step closer; this voice turns a simple idea into a bright little moment",
    ru: "[тепло] Подойди ближе; этот голос превращает простую мысль в яркий момент",
    de: "[warm] Komm näher; diese Stimme macht aus einer Idee einen hellen Moment",
    fa: "[با لبخند] یه قدم نزدیک‌تر بیا؛ این صدا هر جمله ساده رو به یه لحظه درخشان تبدیل می‌کنه",
    tr: "[sıcak] Biraz yaklaş; bu ses basit bir fikri parlak bir ana çevirir",
    ar: "[بدفء] اقترب قليلاً؛ هذا الصوت يحول الفكرة البسيطة إلى لحظة مشرقة",
    zh: "[温暖地] 靠近一点；这个声音把简单想法变成明亮瞬间",
    ja: "[温かく] もう少し近くへ。この声は小さな想いを明るい瞬間に変えます",
    es: "[con calidez] Acércate; esta voz convierte una idea simple en un momento brillante",
    hi: "[गर्मजोशी से] ज़रा पास आइए; यह आवाज़ साधारण विचार को चमकदार पल बना देती है",
  },
  Selena: {
    en: "[soft smile] Your words can feel elegant, close, and impossible to skip",
    ru: "[мягкая улыбка] Твои слова могут звучать изящно, близко и незабываемо",
    de: "[sanft lächelnd] Deine Worte können elegant, nah und unwiderstehlich klingen",
    fa: "[با لبخند آروم] کلماتت می‌تونن شیک، نزدیک و غیرقابل رد شدن شنیده بشن",
    tr: "[yumuşak gülümseme] Sözlerin zarif, yakın ve vazgeçilmez duyulabilir",
    ar: "[بابتسامة هادئة] كلماتك قد تبدو أنيقة وقريبة ولا تُفوَّت",
    zh: "[轻轻微笑] 你的文字可以优雅、亲近、让人舍不得跳过",
    ja: "[やさしい笑顔で] あなたの言葉は上品で近く、聴き逃せないものになります",
    es: "[sonrisa suave] Tus palabras pueden sentirse elegantes, cercanas e imposibles de saltar",
    hi: "[हल्की मुस्कान] आपके शब्द सुरुचिपूर्ण, करीब और अनदेखे न किए जाने वाले लग सकते हैं",
  },
  Vespera: {
    en: "[mysterious] Listen to the demo only; this premium voice holds a cinematic secret",
    ru: "[таинственно] Послушай только демо; этот премиум голос хранит кинематографичный секрет",
    de: "[geheimnisvoll] Hör nur die Demo; diese Premium-Stimme trägt ein filmisches Geheimnis",
    fa: "[مرموز و آرام] فقط دمو رو گوش کن؛ این صدای ویژه یه راز سینمایی تو خودش داره",
    tr: "[gizemli] Sadece demoyu dinle; bu premium ses sinematik bir sır taşıyor",
    ar: "[بغموض] استمع إلى العرض فقط؛ هذا الصوت المميز يحمل سراً سينمائياً",
    zh: "[神秘地] 只听演示吧；这个高级声音藏着电影感的秘密",
    ja: "[神秘的に] デモだけを聴いてください。このプレミアムな声には映画のような秘密があります",
    es: "[misterioso] Escucha solo la demo; esta voz premium guarda un secreto cinematográfico",
    hi: "[रहस्यमय] सिर्फ डेमो सुनिए; यह प्रीमियम आवाज़ एक सिनेमाई राज़ रखती है",
  },
  Elara: {
    en: "[brightly] A tiny sentence can sparkle when the voice knows where to breathe",
    ru: "[светло] Маленькая фраза сияет, когда голос знает где вдохнуть",
    de: "[hell] Ein kleiner Satz funkelt, wenn die Stimme richtig atmet",
    fa: "[روشن و پرانرژی] یه جمله کوتاه وقتی نفس و حس درست داشته باشه، برق می‌زنه",
    tr: "[parlak] Küçük bir cümle doğru nefesle ışıldayabilir",
    ar: "[بإشراق] الجملة الصغيرة تلمع عندما يعرف الصوت أين يتنفس",
    zh: "[明亮地] 当声音懂得呼吸，短短一句也会闪光",
    ja: "[明るく] 声が息づかいを知ると、小さな一文もきらめきます",
    es: "[brillante] Una frase pequeña puede brillar cuando la voz sabe respirar",
    hi: "[उजले स्वर में] सही ठहराव वाली आवाज़ छोटी पंक्ति को भी चमका देती है",
  },
  Atlas: {
    en: "[confident] Give your message weight, rhythm, and a bold modern edge",
    ru: "[уверенно] Придай сообщению вес, ритм и смелый современный характер",
    de: "[selbstbewusst] Gib deiner Botschaft Gewicht, Rhythmus und moderne Stärke",
    fa: "[با اعتمادبه‌نفس] به پیامت وزن، ریتم و یه حس مدرن و جسور بده",
    tr: "[kendinden emin] Mesajına ağırlık, ritim ve modern bir cesaret kat",
    ar: "[بثقة] امنح رسالتك وزناً وإيقاعاً وحضوراً عصرياً جريئاً",
    zh: "[自信地] 给你的信息加上重量、节奏和现代锋芒",
    ja: "[自信を持って] メッセージに重みとリズム、現代的な強さを加えます",
    es: "[con confianza] Dale a tu mensaje peso, ritmo y un toque moderno",
    hi: "[आत्मविश्वास से] अपने संदेश को वजन, लय और आधुनिक अंदाज़ दीजिए",
  },
  Mira: {
    en: "[tenderly] Some words need a gentle voice to feel honest and unforgettable",
    ru: "[нежно] Некоторым словам нужен мягкий голос, чтобы звучать искренне",
    de: "[zärtlich] Manche Worte brauchen eine sanfte Stimme, um ehrlich zu wirken",
    fa: "[لطیف] بعضی کلمه‌ها یه صدای مهربون می‌خوان تا صادق و موندگار شنیده بشن",
    tr: "[nazik] Bazı sözler içten ve kalıcı olmak için yumuşak bir ses ister",
    ar: "[برقة] بعض الكلمات تحتاج صوتاً لطيفاً لتبدو صادقة ولا تُنسى",
    zh: "[温柔地] 有些话需要温柔的声音才显得真诚难忘",
    ja: "[やさしく] 忘れられない誠実さには、やわらかな声が必要な言葉もあります",
    es: "[con ternura] Algunas palabras necesitan una voz suave para sentirse sinceras",
    hi: "[नरमी से] कुछ शब्दों को सच्चा और यादगार बनने के लिए कोमल आवाज़ चाहिए",
  },
  Zoya: {
    en: "[playful] Let the line dance a little, then watch the whole story wake up",
    ru: "[игриво] Пусть строка немного танцует, и вся история оживает",
    de: "[verspielt] Lass die Zeile tanzen, dann erwacht die ganze Geschichte",
    fa: "[بازیگوش] بذار جمله یه کم برقصد؛ بعد می‌بینی کل داستان زنده می‌شه",
    tr: "[oyuncu] Cümle biraz dans etsin, sonra hikaye canlansın",
    ar: "[بمرح] دع الجملة ترقص قليلاً، وستستيقظ القصة كلها",
    zh: "[俏皮地] 让句子轻轻跳舞，整个故事就醒来了",
    ja: "[遊び心を込めて] 一文を少し踊らせると、物語全体が目を覚まします",
    es: "[juguetona] Deja que la frase baile un poco y la historia despertará",
    hi: "[चुलबुले अंदाज़ में] पंक्ति को थोड़ा नाचने दीजिए, कहानी जाग उठेगी",
  },
  Kiara: {
    en: "[excited whisper] This is how a fresh voice makes your first second unforgettable",
    ru: "[взволнованный шепот] Так свежий голос делает первую секунду незабываемой",
    de: "[aufgeregtes Flüstern] So macht eine frische Stimme die erste Sekunde unvergesslich",
    fa: "[نجوای هیجان‌زده] اینطوری یه صدای تازه همون ثانیه اول تو ذهن می‌مونه",
    tr: "[heyecanlı fısıltı] Taze bir ses ilk saniyeyi böyle unutulmaz yapar",
    ar: "[همسة متحمسة] هكذا يجعل الصوت الجديد أول ثانية لا تُنسى",
    zh: "[兴奋低语] 新鲜的声音就是这样让第一秒难忘",
    ja: "[弾むささやき] 新鮮な声は最初の一秒を忘れられなくします",
    es: "[susurro emocionado] Así una voz fresca vuelve inolvidable el primer segundo",
    hi: "[उत्साहित फुसफुसाहट] ताज़ा आवाज़ पहला सेकंड ऐसे यादगार बना देती है",
  },
  Ryder: {
    en: "[boldly] When the voice hits with style, even a short line feels iconic",
    ru: "[смело] Когда голос звучит стильно, даже короткая строка становится яркой",
    de: "[kühn] Wenn die Stimme Stil hat, wirkt selbst eine kurze Zeile ikonisch",
    fa: "[جسور] وقتی صدا با استایل بیاد، حتی یه خط کوتاه هم آیکونیک می‌شه",
    tr: "[cesur] Ses stil sahibi olunca kısa bir satır bile ikonik gelir",
    ar: "[بجرأة] عندما يصل الصوت بأناقة، حتى السطر القصير يصبح أيقونياً",
    zh: "[大胆地] 声音有风格时，短短一句也像经典台词",
    ja: "[大胆に] 声にスタイルがあると、短い一文さえ象徴的に響きます",
    es: "[audaz] Cuando la voz llega con estilo, una línea breve se vuelve icónica",
    hi: "[दमदार] स्टाइल वाली आवाज़ छोटी पंक्ति को भी आइकॉनिक बना देती है",
  },

  Lyra: {
    en: "[giggles] This voice turns tiny ideas into bright moments people remember",
    fa: "[giggles] این صدا ایده‌های کوچیک رو به لحظه‌های روشن و موندگار تبدیل می‌کنه",
  },
  Zane: {
    en: "[speaks softly] Clean words, calm rhythm, and a modern voice that stays with you",
    fa: "[speaks softly] کلمه‌های تمیز، ریتم آروم، و صدایی مدرن که تو ذهن می‌مونه",
  },
  Knox: {
    en: "[sighs] A deep tone can make even one simple line feel cinematic",
    fa: "[sighs] یه لحن عمیق حتی یک خط ساده رو هم سینمایی و خاص می‌کنه",
  },
  Jaxon: {
    en: "[shouts] Bring the energy in fast, then let the last word land clean",
    fa: "[shouts] انرژی رو سریع بیار بالا، بعد بذار کلمه آخر تمیز بشینه",
  },
  Ace: {
    en: "[angry] When the message needs impact, this voice cuts straight through",
    fa: "[angry] وقتی پیام باید ضربه بزنه، این صدا مستقیم و محکم عبور می‌کنه",
  },
  Cruz: {
    en: "[laughs] Keep it smooth, keep it real, and every sentence feels closer",
    fa: "[laughs] روان و واقعی نگهش دار، تا هر جمله نزدیک‌تر حس بشه",
  },
  Neo: {
    en: "[gasps] A fresh futuristic sound can make short text feel brand new",
    fa: "[gasps] یه صدای تازه و آینده‌نگر متن کوتاه رو کاملاً نو نشون می‌ده",
  },
  Skye: {
    en: "[whispers] Soft words can still shine when the voice carries real emotion",
    fa: "[whispers] کلمه‌های آروم هم وقتی صدا احساس واقعی داشته باشه می‌درخشن",
  },
  Kairo: {
    en: "[speaks softly] Give your story a premium pulse with calm confident style",
    fa: "[speaks softly] به داستانت با استایل آروم و مطمئن، حس پریمیوم بده",
  },
  Sia: {
    en: "[giggles] Hey, your turn now; I’m listening, so tell me what happened next",
    fa: "[giggles] خب نوبت توئه؛ گوش می‌دم، بگو بعدش چی شد",
  },
  Milo: {
    en: "[laughs] That actually makes sense; let’s talk it through one step at a time",
    fa: "[laughs] راستش منطقیه؛ بیا قدم‌به‌قدم درباره‌ش حرف بزنیم",
  },
  Rhea: {
    en: "[speaks softly] I get you; say it your way, and I’ll follow the feeling",
    fa: "[speaks softly] می‌فهممت؛ به روش خودت بگو، من حسش رو دنبال می‌کنم",
  },
  Orion: {
    en: "A sharp confident voice can carry your message with power and style",
    ru: "Четкий уверенный голос передает сообщение с силой и стилем",
    de: "Eine klare selbstsichere Stimme trägt deine Botschaft mit Kraft und Stil",
    fa: "یه صدای تیز و مطمئن پیام تو رو با قدرت و استایل منتقل می‌کنه",
    tr: "Keskin ve kendinden emin bir ses mesajını güç ve tarzla taşır",
    ar: "الصوت الواثق والواضح يحمل رسالتك بقوة وأناقة",
    zh: "清晰自信的声音能有力又有风格地传达信息",
    ja: "鋭く自信のある声がメッセージを力強くスタイリッシュに届けます",
    es: "Una voz nítida y segura lleva tu mensaje con fuerza y estilo",
    hi: "तेज़ और आत्मविश्वासी आवाज़ आपका संदेश ताकत और अंदाज़ से पहुँचाती है",
  },
};

export function getDemoText(language, voice) {
  const lang = language || "en";
  return DEMO_TEXTS[voice]?.[lang] || DEMO_TEXTS[voice]?.en || DEMO_TEXTS.Nora[lang] || DEMO_TEXTS.Nora.en;
}
