import { formatUsdBalanceFromCredits, formatUsdChargeFromCredits } from "./credits.js";

export const LANGUAGES = {
  en: "English",
  ru: "Русский",
  de: "Deutsch",
  fa: "فارسی",
  tr: "Türkçe",
  ar: "العربية",
  zh: "中文",
  ja: "日本語",
  es: "Español",
  hi: "हिन्दी",
};

const M = {
  en: { moreVoices: "More voices", vexaDownloaderText: "Download videos from YouTube, Instagram, Pornhub, and other platforms in the quality you want, and add subtitles in any language you like.\n\nSend your video link and let’s go 👇", vexaDownloaderButton: "🪼 Download & add subtitles", vexaImageText: "Describe anything you have in mind, or upload your photo and recreate it in a fresh style.\n\nNeed inspiration? Pick any image you like in <b>Explore</b> — its prompt is ready, so you can create it instantly with your own photo.\n\nGot an idea? Let’s make it 👇", vexaImageButton: "🪄 Start creating", vexaAiChatText: "Chat with Vexa, send a photo or file, and get help with your ideas, work, or coding.\n\nYou can connect GitHub too, so Vexa can be right there with your repositories. The model and how deeply it thinks are up to you.\n\nWhat’s on your mind? 👇", vexaAiChatButton: "🐙 Start chatting with Vexa",
    chooseLanguageTitle: "🌐 <b>Choose your language</b>", chooseLanguageSubtitle: "Please select your language to continue", ttsTitle: "🎧 <b>Text to Speech</b>", sendText: "Send your text or a voice message", creditRule: "TTS costs <b>$0.00017 per character</b>", audioCreditRule: "Voice Transform V3 uses the same per-character TTS rate", selectedVoice: "Selected voice", demo: "▶ Demo", next: "Next →", previous: "← Previous", balance: "💎 Balance", buyCredits: "⚡ Add Balance", balancePopup: "Your balance:\n\n{balance}", buyTitle: "💳 <b>Add Balance</b>", priceLine: "Your balance is shown in <b>USD</b>", choosePayment: "Choose a payment method", buyToman: "🇮🇷 Pay with Toman", telegramStars: "⭐ Telegram Stars", back: "← Back", buyTomanTitle: "🇮🇷 <b>Pay with Toman</b>", choosePackage: "Choose an amount", almostThere: "🔥 <b>Almost there!</b>", package: "Balance", amount: "Amount", transfer: "Please transfer the exact amount to this card number:", sendScreenshot: "Then send your payment screenshot right here", verification: "Your balance will be added after verification", cancel: "Cancel", generatingDemo: "Generating demo", generatingVoice: "Generating voice", notEnough: "Not enough balance\nNeeded: {needed}\nBalance: {balance}", screenshotNoPackage: "Screenshot received. Please choose a balance amount first", screenshotReceived: "✅ <b>Payment screenshot received!</b>", receiptWaiting: "Your receipt is now waiting for admin verification", creditsAfterApproval: "After approval, the amount will be added to your balance", keepUsing: "You can keep using the bot or choose another option below", comingSoon: "Coming soon", invalidPackage: "Invalid amount", ttsError: "TTS Error", accessDenied: "Access denied", demoText: "Hello, this is a free demo voice from Vexa text to speech"
  },
  fa: { moreVoices: "صداهای بیشتر", vexaDownloaderText: "ویدیوهای موردعلاقه‌ت رو از YouTube، Instagram، Pornhub و پلتفرم‌های دیگه با کیفیت دلخواه دانلود کن و به هر زبانی که می‌خوای براشون زیرنویس بذار.\n\nلینک ویدیو رو بفرست تا شروع کنیم 👇", vexaDownloaderButton: "🪼 دانلود و افزودن زیرنویس", vexaImageText: "هرچیزی توی ذهنت داری رو توصیف کن، یا عکست رو آپلود کن و با یه استایل تازه بسازش.\n\nایده نداری؟ توی <b>Explore</b> هر تصویری که دوست داشتی انتخاب کن؛ پرامپتش از قبل آماده‌ست و می‌تونی همون لحظه با عکس خودت بسازیش.\n\nایده‌ت آماده‌ست؟ بریم بسازیمش 👇", vexaImageButton: "🪄 شروع ساخت تصویر", vexaAiChatText: "با Vexa حرف بزن، عکس یا فایل بفرست و برای ایده‌هات، کارهات یا کدنویسی کمک بگیر.\n\nمی‌تونی GitHub رو هم وصل کنی تا روی ریپوهات کنارت باشه. مدل و میزان فکرکردنش هم دست خودته.\n\nچی توی ذهنته؟ 👇", vexaAiChatButton: "🐙 شروع چت با Vexa", chooseLanguageTitle: "🌐 <b>زبان را انتخاب کن</b>", chooseLanguageSubtitle: "برای ادامه زبان خودت را انتخاب کن", ttsTitle: "🎧 <b>تبدیل متن به صدا</b>", sendText: "متنتو بنویس یا ویس بفرست", creditRule: "هزینه TTS برای هر کاراکتر <b>$0.00017</b> است", audioCreditRule: "Voice Transform V3 هم با همین نرخ هر کاراکتر محاسبه می‌شود", selectedVoice: "صدای انتخاب‌شده", demo: "▶ دموی صدا", next: "بعدی →", previous: "← قبلی", balance: "💎 موجودی", buyCredits: "⚡ افزایش موجودی", balancePopup: "موجودی شما:\n\n{balance}", buyTitle: "💳 <b>افزایش موجودی</b>", priceLine: "موجودی حساب با <b>دلار</b> نمایش داده می‌شود", choosePayment: "روش پرداخت را انتخاب کن", buyToman: "🇮🇷 پرداخت با تومان", telegramStars: "⭐ استارز تلگرام", back: "← برگشت", buyTomanTitle: "🇮🇷 <b>پرداخت با تومان</b>", choosePackage: "مقدار موردنظر را انتخاب کن", almostThere: "🔥 <b>تقریباً تمومه!</b>", package: "موجودی", amount: "مبلغ", transfer: "مبلغ دقیق را به این شماره کارت واریز کن:", sendScreenshot: "بعد اسکرین‌شات پرداخت را همینجا بفرست", verification: "بعد از تایید، مبلغ به موجودی حسابت اضافه می‌شود", cancel: "لغو", generatingDemo: "در حال ساخت دمو", generatingVoice: "در حال ساخت صدا", notEnough: "موجودی کافی نیست\nنیاز: {needed}\nموجودی: {balance}", screenshotNoPackage: "اسکرین‌شات دریافت شد. اول مقدار موجودی موردنظرت را انتخاب کن", screenshotReceived: "✅ <b>اسکرین‌شات پرداخت دریافت شد!</b>", receiptWaiting: "رسید شما منتظر تایید ادمین است", creditsAfterApproval: "بعد از تایید، مبلغ به موجودی حسابت اضافه می‌شود", keepUsing: "می‌توانی از ربات استفاده کنی یا گزینه‌ای انتخاب کنی", comingSoon: "به‌زودی", invalidPackage: "مقدار نامعتبر است", ttsError: "خطای تبدیل صدا", accessDenied: "دسترسی غیرمجاز", demoText: "سلام، این یک دموی رایگان از صدای هوش مصنوعی وکسا است" },
  ru: { moreVoices: "Больше голосов", vexaDownloaderText: "Скачивай любимые видео с YouTube, Instagram, Pornhub и других платформ в нужном качестве и добавляй субтитры на любом языке.\n\nОтправь ссылку на видео — и начнём 👇", vexaDownloaderButton: "🪼 Скачать и добавить субтитры", vexaImageText: "Опиши всё, что представляешь, или загрузи своё фото и создай его в новом стиле.\n\nНе хватает идей? Выбери любую понравившуюся картинку в <b>Explore</b> — промпт уже готов, и ты сразу сможешь создать её со своим фото.\n\nИдея готова? Давай воплотим её 👇", vexaImageButton: "🪄 Начать создавать", vexaAiChatText: "Общайся с Vexa, отправляй фото или файлы и получай помощь с идеями, задачами или программированием.\n\nМожно подключить GitHub, чтобы Vexa был рядом с твоими репозиториями. Модель и глубину размышлений выбираешь ты.\n\nЧто у тебя на уме? 👇", vexaAiChatButton: "🐙 Начать чат с Vexa", chooseLanguageTitle: "🌐 <b>Выберите язык</b>", chooseLanguageSubtitle: "Выберите язык, чтобы продолжить", ttsTitle: "🎧 <b>Текст в речь</b>", sendText: "Отправьте текст или голосовое сообщение", creditRule: "TTS стоит <b>$0.00017 за символ</b>", selectedVoice: "Выбранный голос", demo: "▶ Демо", next: "Далее →", previous: "← Назад", balance: "💎 Баланс", buyCredits: "⚡ Пополнить баланс", choosePayment: "Выберите способ оплаты", buyToman: "🇮🇷 Оплата в томанах", telegramStars: "⭐ Telegram Stars", back: "← Назад", cancel: "Отмена", generatingDemo: "Создаю демо", generatingVoice: "Создаю голос", comingSoon: "Скоро", accessDenied: "Доступ запрещен", demoText: "Здравствуйте, это бесплатная демонстрация голоса Vexa" },
  de: { moreVoices: "Mehr Stimmen", vexaDownloaderText: "Lade deine Lieblingsvideos von YouTube, Instagram, Pornhub und anderen Plattformen in deiner Wunschqualität herunter und füge Untertitel in deiner Sprache hinzu.\n\nSchick einfach den Videolink und los geht’s 👇", vexaDownloaderButton: "🪼 Herunterladen & untertiteln", vexaImageText: "Beschreibe, was du dir vorstellst, oder lade dein Foto hoch und gestalte es in einem neuen Stil.\n\nNoch keine Idee? Such dir in <b>Explore</b> ein Bild aus, das dir gefällt — der Prompt ist schon fertig und du kannst es direkt mit deinem eigenen Foto erstellen.\n\nIdee im Kopf? Lass sie uns umsetzen 👇", vexaImageButton: "🪄 Bild erstellen", vexaAiChatText: "Unterhalte dich mit Vexa, sende ein Foto oder eine Datei und hol dir Hilfe bei Ideen, Aufgaben oder beim Programmieren.\n\nDu kannst auch GitHub verbinden, damit Vexa direkt bei deinen Repositories dabei ist. Modell und Denkintensität bestimmst du selbst.\n\nWas geht dir durch den Kopf? 👇", vexaAiChatButton: "🐙 Chat mit Vexa starten", chooseLanguageTitle: "🌐 <b>Sprache wählen</b>", chooseLanguageSubtitle: "Bitte wähle deine Sprache", ttsTitle: "🎧 <b>Text zu Sprache</b>", sendText: "Sende deinen Text oder eine Sprachnachricht", creditRule: "TTS kostet <b>$0.00017 pro Zeichen</b>", selectedVoice: "Ausgewählte Stimme", demo: "▶ Demo", next: "Weiter →", previous: "← Zurück", balance: "💎 Guthaben", buyCredits: "⚡ Guthaben aufladen", choosePayment: "Zahlungsmethode wählen", buyToman: "🇮🇷 Mit Toman bezahlen", telegramStars: "⭐ Telegram Stars", back: "← Zurück", cancel: "Abbrechen", generatingDemo: "Demo wird erstellt", generatingVoice: "Stimme wird erstellt", comingSoon: "Bald verfügbar", accessDenied: "Zugriff verweigert", demoText: "Hallo, dies ist eine kostenlose Demo der Vexa KI-Stimme" },
  tr: { moreVoices: "Daha fazla ses", vexaDownloaderText: "Sevdiğin videoları YouTube, Instagram, Pornhub ve diğer platformlardan istediğin kalitede indir, dilediğin dilde altyazı ekle.\n\nVideo bağlantısını gönder, hemen başlayalım 👇", vexaDownloaderButton: "🪼 İndir ve altyazı ekle", vexaImageText: "Aklındaki her şeyi anlat ya da fotoğrafını yükleyip yepyeni bir stille oluştur.\n\nAklına bir şey gelmiyor mu? <b>Explore</b>’da beğendiğin görseli seç — promptu hazır, kendi fotoğrafınla hemen oluşturabilirsin.\n\nFikrin hazır mı? Hadi oluşturalım 👇", vexaImageButton: "🪄 Görsel oluşturmaya başla", vexaAiChatText: "Vexa’yla konuş, fotoğraf ya da dosya gönder; fikirlerin, işlerin veya kodlama için destek al.\n\nGitHub’ı da bağlayabilirsin; böylece Vexa repolarında yanında olur. Modeli ve ne kadar düşüneceğini sen seçersin.\n\nAklında ne var? 👇", vexaAiChatButton: "🐙 Vexa ile sohbete başla", chooseLanguageTitle: "🌐 <b>Dil seç</b>", chooseLanguageSubtitle: "Devam etmek için dilini seç", ttsTitle: "🎧 <b>Metinden sese</b>", sendText: "Metnini veya sesli mesajını gönder", creditRule: "TTS ücreti karakter başına <b>$0.00017</b>", selectedVoice: "Seçilen ses", demo: "▶ Demo", next: "İleri →", previous: "← Geri", balance: "💎 Bakiye", buyCredits: "⚡ Bakiye yükle", choosePayment: "Ödeme yöntemi seç", buyToman: "🇮🇷 Toman ile öde", telegramStars: "⭐ Telegram Stars", back: "← Geri", cancel: "İptal", generatingDemo: "Demo oluşturuluyor", generatingVoice: "Ses oluşturuluyor", comingSoon: "Yakında", accessDenied: "Erişim reddedildi", demoText: "Merhaba, bu Vexa yapay zeka sesinin ücretsiz demosudur" },
  ar: { moreVoices: "المزيد من الأصوات", vexaDownloaderText: "حمّل فيديوهاتك المفضلة من YouTube وInstagram وPornhub ومنصات أخرى بالجودة التي تناسبك، وأضف لها ترجمة باللغة التي تريدها.\n\nأرسل رابط الفيديو ولنبدأ 👇", vexaDownloaderButton: "🪼 تنزيل وإضافة ترجمة", vexaImageText: "اوصف أي شيء في بالك، أو ارفع صورتك واصنعها بأسلوب جديد.\n\nما عندك فكرة؟ اختر أي صورة تعجبك من <b>Explore</b> — البرومبت جاهز، وتقدر تصنعها فوراً بصورتك.\n\nفكرتك جاهزة؟ يلا نصنعها 👇", vexaImageButton: "🪄 ابدأ صنع الصورة", vexaAiChatText: "تكلّم مع Vexa، أرسل صورة أو ملفاً، وخذ المساعدة في أفكارك أو عملك أو البرمجة.\n\nتقدر تربط GitHub أيضاً حتى يكون Vexa معك في مستودعاتك. أنت تختار النموذج وعمق التفكير.\n\nوش في بالك؟ 👇", vexaAiChatButton: "🐙 ابدأ الدردشة مع Vexa", chooseLanguageTitle: "🌐 <b>اختر اللغة</b>", chooseLanguageSubtitle: "اختر لغتك للمتابعة", ttsTitle: "🎧 <b>تحويل النص إلى صوت</b>", sendText: "أرسل النص أو رسالة صوتية", creditRule: "تكلفة TTS هي <b>$0.00017 لكل حرف</b>", selectedVoice: "الصوت المختار", demo: "▶ تجربة", next: "التالي →", previous: "← السابق", balance: "💎 الرصيد", buyCredits: "⚡ شحن الرصيد", choosePayment: "اختر طريقة الدفع", buyToman: "🇮🇷 الدفع بالتومان", telegramStars: "⭐ نجوم تيليجرام", back: "← رجوع", cancel: "إلغاء", generatingDemo: "جاري إنشاء التجربة", generatingVoice: "جاري إنشاء الصوت", comingSoon: "قريباً", accessDenied: "تم رفض الوصول", demoText: "مرحباً، هذا عرض مجاني لصوت فيكسا بالذكاء الاصطناعي" },
  zh: { moreVoices: "更多声音", vexaDownloaderText: "从 YouTube、Instagram、Pornhub 等平台下载你喜欢的视频，自由选择画质，还能添加你想要的语言字幕。\n\n把视频链接发来，马上开始 👇", vexaDownloaderButton: "🪼 下载并添加字幕", vexaImageText: "描述你脑海中的任何画面，或者上传自己的照片，换一种全新风格来创作。\n\n没灵感？去 <b>Explore</b> 挑一张喜欢的图片——提示词已经准备好了，马上就能用自己的照片生成。\n\n想法准备好了吗？一起把它做出来 👇", vexaImageButton: "🪄 开始创作图片", vexaAiChatText: "和 Vexa 聊聊，发送图片或文件，在灵感、工作或编程上获得帮助。\n\n你也可以连接 GitHub，让 Vexa 陪你处理自己的仓库。模型和思考深度都由你决定。\n\n你在想什么？ 👇", vexaAiChatButton: "🐙 开始与 Vexa 聊天", chooseLanguageTitle: "🌐 <b>选择语言</b>", chooseLanguageSubtitle: "请选择语言继续", ttsTitle: "🎧 <b>文字转语音</b>", sendText: "发送文本或语音消息", creditRule: "TTS 每个字符收费 <b>$0.00017</b>", selectedVoice: "已选声音", demo: "▶ 试听", next: "下一页 →", previous: "← 上一页", balance: "💎 余额", buyCredits: "⚡ 充值余额", choosePayment: "选择支付方式", buyToman: "🇮🇷 使用 Toman 支付", telegramStars: "⭐ Telegram Stars", back: "← 返回", cancel: "取消", generatingDemo: "正在生成试听", generatingVoice: "正在生成语音", comingSoon: "即将推出", accessDenied: "拒绝访问", demoText: "你好，这是 Vexa 人工智能语音的免费试听" },
  ja: { moreVoices: "さらに音声", vexaDownloaderText: "YouTube、Instagram、Pornhub などのお気に入り動画を、好きな画質でダウンロード。好きな言語の字幕も追加できます。\n\n動画リンクを送って、さっそく始めよう 👇", vexaDownloaderButton: "🪼 ダウンロード＆字幕追加", vexaImageText: "頭に浮かんだものを言葉にするか、自分の写真をアップロードして新しいスタイルで作ってみよう。\n\nアイデアが浮かばない？ <b>Explore</b> で好きな画像を選べば、プロンプトはすでに用意済み。自分の写真ですぐに作れます。\n\nイメージは決まった？ さっそく作ろう 👇", vexaImageButton: "🪄 画像を作り始める", vexaAiChatText: "Vexa と話して、写真やファイルを送り、アイデアや仕事、プログラミングの相談をしよう。\n\nGitHub もつなげられるから、リポジトリの作業も Vexa がそばでサポート。モデルや考える深さも自分で選べます。\n\n今、何を考えてる？ 👇", vexaAiChatButton: "🐙 Vexa とチャットを始める", chooseLanguageTitle: "🌐 <b>言語を選択</b>", chooseLanguageSubtitle: "続行する言語を選択してください", ttsTitle: "🎧 <b>テキスト読み上げ</b>", sendText: "テキストまたはボイスメッセージを送信", creditRule: "TTS は1文字あたり <b>$0.00017</b>", selectedVoice: "選択中の音声", demo: "▶ デモ", next: "次へ →", previous: "← 戻る", balance: "💎 残高", buyCredits: "⚡ 残高をチャージ", choosePayment: "支払い方法を選択", buyToman: "🇮🇷 Tomanで支払う", telegramStars: "⭐ Telegram Stars", back: "← 戻る", cancel: "キャンセル", generatingDemo: "デモ生成中", generatingVoice: "音声生成中", comingSoon: "近日公開", accessDenied: "アクセス拒否", demoText: "こんにちは、これは Vexa AI 音声の無料デモです" },
  es: { moreVoices: "Más voces", vexaDownloaderText: "Descarga tus vídeos favoritos de YouTube, Instagram, Pornhub y otras plataformas con la calidad que quieras, y añade subtítulos en el idioma que prefieras.\n\nManda el enlace del vídeo y empezamos 👇", vexaDownloaderButton: "🪼 Descargar y añadir subtítulos", vexaImageText: "Describe cualquier cosa que tengas en mente o sube tu foto y créala con un estilo nuevo.\n\n¿Sin ideas? Elige la imagen que más te guste en <b>Explore</b> — el prompt ya está listo y puedes crearla al instante con tu propia foto.\n\n¿Ya tienes una idea? Vamos a crearla 👇", vexaImageButton: "🪄 Empezar a crear", vexaAiChatText: "Habla con Vexa, envía una foto o un archivo y recibe ayuda con tus ideas, tu trabajo o la programación.\n\nTambién puedes conectar GitHub para tener a Vexa a tu lado en tus repositorios. Tú eliges el modelo y cuánto quieres que piense.\n\n¿Qué tienes en mente? 👇", vexaAiChatButton: "🐙 Empezar a chatear con Vexa", chooseLanguageTitle: "🌐 <b>Elige tu idioma</b>", chooseLanguageSubtitle: "Selecciona tu idioma para continuar", ttsTitle: "🎧 <b>Texto a voz</b>", sendText: "Envía tu texto o un mensaje de voz", creditRule: "TTS cuesta <b>$0.00017 por carácter</b>", selectedVoice: "Voz seleccionada", demo: "▶ Demo", next: "Siguiente →", previous: "← Anterior", balance: "💎 Saldo", buyCredits: "⚡ Recargar saldo", choosePayment: "Elige un método de pago", buyToman: "🇮🇷 Pagar con Toman", telegramStars: "⭐ Telegram Stars", back: "← Volver", cancel: "Cancelar", generatingDemo: "Generando demo", generatingVoice: "Generando voz", comingSoon: "Próximamente", accessDenied: "Acceso denegado", demoText: "Hola, esta es una demostración gratuita de la voz de inteligencia artificial de Vexa" },
  hi: { moreVoices: "और आवाज़ें", vexaDownloaderText: "YouTube, Instagram, Pornhub और दूसरे प्लेटफ़ॉर्म से अपने पसंदीदा वीडियो मनचाही क्वालिटी में डाउनलोड करो और अपनी पसंद की भाषा में सबटाइटल जोड़ो।\n\nवीडियो लिंक भेजो और शुरू करते हैं 👇", vexaDownloaderButton: "🪼 डाउनलोड और सबटाइटल जोड़ें", vexaImageText: "जो भी तुम्हारे मन में है उसे बताओ, या अपनी फोटो अपलोड करके उसे एक नए स्टाइल में बनाओ।\n\nकोई आइडिया नहीं? <b>Explore</b> में अपनी पसंद की तस्वीर चुनो — उसका प्रॉम्प्ट पहले से तैयार है और तुम उसे अपनी फोटो के साथ तुरंत बना सकते हो।\n\nआइडिया तैयार है? चलो इसे बनाते हैं 👇", vexaImageButton: "🪄 इमेज बनाना शुरू करें", vexaAiChatText: "Vexa से बात करो, फोटो या फ़ाइल भेजो और अपने आइडिया, काम या कोडिंग में मदद पाओ।\n\nGitHub भी कनेक्ट कर सकते हो, ताकि Vexa तुम्हारे रिपॉज़िटरी के साथ रहे। मॉडल और सोचने की गहराई तुम खुद चुनते हो।\n\nतुम्हारे मन में क्या है? 👇", vexaAiChatButton: "🐙 Vexa के साथ चैट शुरू करें", chooseLanguageTitle: "🌐 <b>भाषा चुनें</b>", chooseLanguageSubtitle: "जारी रखने के लिए अपनी भाषा चुनें", ttsTitle: "🎧 <b>टेक्स्ट टू स्पीच</b>", sendText: "अपना टेक्स्ट या वॉइस मैसेज भेजें", creditRule: "TTS की कीमत प्रति अक्षर <b>$0.00017</b> है", selectedVoice: "चुनी गई आवाज़", demo: "▶ डेमो", next: "आगे →", previous: "← पीछे", balance: "💎 बैलेंस", buyCredits: "⚡ बैलेंस जोड़ें", choosePayment: "पेमेंट तरीका चुनें", buyToman: "🇮🇷 Toman से भुगतान", telegramStars: "⭐ Telegram Stars", back: "← वापस", cancel: "रद्द करें", generatingDemo: "डेमो बन रहा है", generatingVoice: "आवाज़ बन रही है", comingSoon: "जल्द आ रहा है", accessDenied: "एक्सेस मना है", demoText: "नमस्ते, यह Vexa एआई आवाज़ का मुफ्त डेमो है" },
};

export function normalizeLang(lang) { return LANGUAGES[lang] ? lang : "en"; }
export function t(lang, key, vars = {}) {
  const code = normalizeLang(lang || "en");
  let text = M[code]?.[key] || M.en[key] || key;
  const values = { ...vars };
  if (key === "balancePopup" && values.balance != null) {
    values.balance = formatUsdBalanceFromCredits(values.balance);
  }
  if (key === "notEnough") {
    if (values.needed != null) values.needed = formatUsdChargeFromCredits(values.needed);
    if (values.balance != null) values.balance = formatUsdBalanceFromCredits(values.balance);
  }
  for (const [k, v] of Object.entries(values)) text = text.replaceAll("{" + k + "}", String(v));
  return text;
}
