import { formatUsdBalanceFromCredits, formatUsdChargeFromCredits } from "./credits.js";

export const LANGUAGES = {
  en: "English",
  ru: "Русский",
  de: "Deutsch",
  fa: "فارسی",
  tr: "Türkçe",
  ar: "العربية",
  zh: "中文",
  ja: "日本語",
  es: "Español",
  hi: "हिन्दी",
};

const M = {
  en: { moreVoices: "More voices",
    chooseLanguageTitle: "🌐 <b>Choose your language</b>", chooseLanguageSubtitle: "Please select your language to continue", ttsTitle: "🎧 <b>Text to Speech</b>", sendText: "Send your text", creditRule: "TTS costs <b>$0.00017 per character</b>", audioCreditRule: "Voice Transform V3 uses the same per-character TTS rate", selectedVoice: "Selected voice", demo: "▶ Demo", next: "Next →", previous: "← Previous", balance: "💎 Balance", buyCredits: "⚡ Add Balance", balancePopup: "Your balance:\n\n<b>{balance}</b>", buyTitle: "💳 <b>Add Balance</b>", priceLine: "Your balance is shown in <b>USD</b>", choosePayment: "Choose a payment method", buyToman: "🇮🇷 Pay with Toman", telegramStars: "⭐ Telegram Stars", back: "← Back", buyTomanTitle: "🇮🇷 <b>Pay with Toman</b>", choosePackage: "Choose an amount", almostThere: "🔥 <b>Almost there!</b>", package: "Balance", amount: "Amount", transfer: "Please transfer the exact amount to this card number:", sendScreenshot: "Then send your payment screenshot right here", verification: "Your balance will be added after verification", cancel: "Cancel", generatingDemo: "Generating demo", generatingVoice: "Generating voice", notEnough: "Not enough balance\nNeeded: {needed}\nBalance: {balance}", screenshotNoPackage: "Screenshot received. Please choose a balance amount first", screenshotReceived: "✅ <b>Payment screenshot received!</b>", receiptWaiting: "Your receipt is now waiting for admin verification", creditsAfterApproval: "After approval, the amount will be added to your balance", keepUsing: "You can keep using the bot or choose another option below", comingSoon: "Coming soon", invalidPackage: "Invalid amount", ttsError: "TTS Error", accessDenied: "Access denied", demoText: "Hello, this is a free demo voice from Vexa text to speech"
  },
  fa: { moreVoices: "صداهای بیشتر", chooseLanguageTitle: "🌐 <b>زبان را انتخاب کن</b>", chooseLanguageSubtitle: "برای ادامه زبان خودت را انتخاب کن", ttsTitle: "🎧 <b>تبدیل متن به صدا</b>", sendText: "متنت را بفرست", creditRule: "هزینه TTS برای هر کاراکتر <b>$0.00017</b> است", audioCreditRule: "Voice Transform V3 هم با همین نرخ هر کاراکتر محاسبه می‌شود", selectedVoice: "صدای انتخاب‌شده", demo: "▶ دموی صدا", next: "بعدی →", previous: "← قبلی", balance: "💎 موجودی", buyCredits: "⚡ افزایش موجودی", balancePopup: "موجودی شما:\n\n<b>{balance}</b>", buyTitle: "💳 <b>افزایش موجودی</b>", priceLine: "موجودی حساب با <b>دلار</b> نمایش داده می‌شود", choosePayment: "روش پرداخت را انتخاب کن", buyToman: "🇮🇷 پرداخت با تومان", telegramStars: "⭐ استارز تلگرام", back: "← برگشت", buyTomanTitle: "🇮🇷 <b>پرداخت با تومان</b>", choosePackage: "مقدار موردنظر را انتخاب کن", almostThere: "🔥 <b>تقریباً تمومه!</b>", package: "موجودی", amount: "مبلغ", transfer: "مبلغ دقیق را به این شماره کارت واریز کن:", sendScreenshot: "بعد اسکرین‌شات پرداخت را همینجا بفرست", verification: "بعد از تایید، مبلغ به موجودی حسابت اضافه می‌شود", cancel: "لغو", generatingDemo: "در حال ساخت دمو", generatingVoice: "در حال ساخت صدا", notEnough: "موجودی کافی نیست\nنیاز: {needed}\nموجودی: {balance}", screenshotNoPackage: "اسکرین‌شات دریافت شد. اول مقدار موجودی موردنظرت را انتخاب کن", screenshotReceived: "✅ <b>اسکرین‌شات پرداخت دریافت شد!</b>", receiptWaiting: "رسید شما منتظر تایید ادمین است", creditsAfterApproval: "بعد از تایید، مبلغ به موجودی حسابت اضافه می‌شود", keepUsing: "می‌توانی از ربات استفاده کنی یا گزینه‌ای انتخاب کنی", comingSoon: "به‌زودی", invalidPackage: "مقدار نامعتبر است", ttsError: "خطای تبدیل صدا", accessDenied: "دسترسی غیرمجاز", demoText: "سلام، این یک دموی رایگان از صدای هوش مصنوعی وکسا است" },
  ru: { moreVoices: "Больше голосов", chooseLanguageTitle: "🌐 <b>Выберите язык</b>", chooseLanguageSubtitle: "Выберите язык, чтобы продолжить", ttsTitle: "🎧 <b>Текст в речь</b>", sendText: "Отправьте текст", creditRule: "TTS стоит <b>$0.00017 за символ</b>", selectedVoice: "Выбранный голос", demo: "▶ Демо", next: "Далее →", previous: "← Назад", balance: "💎 Баланс", buyCredits: "⚡ Пополнить баланс", choosePayment: "Выберите способ оплаты", buyToman: "🇮🇷 Оплата в томанах", telegramStars: "⭐ Telegram Stars", back: "← Назад", cancel: "Отмена", generatingDemo: "Создаю демо", generatingVoice: "Создаю голос", comingSoon: "Скоро", accessDenied: "Доступ запрещен", demoText: "Здравствуйте, это бесплатная демонстрация голоса Vexa" },
  de: { moreVoices: "Mehr Stimmen", chooseLanguageTitle: "🌐 <b>Sprache wählen</b>", chooseLanguageSubtitle: "Bitte wähle deine Sprache", ttsTitle: "🎧 <b>Text zu Sprache</b>", sendText: "Sende deinen Text", creditRule: "TTS kostet <b>$0.00017 pro Zeichen</b>", selectedVoice: "Ausgewählte Stimme", demo: "▶ Demo", next: "Weiter →", previous: "← Zurück", balance: "💎 Guthaben", buyCredits: "⚡ Guthaben aufladen", choosePayment: "Zahlungsmethode wählen", buyToman: "🇮🇷 Mit Toman bezahlen", telegramStars: "⭐ Telegram Stars", back: "← Zurück", cancel: "Abbrechen", generatingDemo: "Demo wird erstellt", generatingVoice: "Stimme wird erstellt", comingSoon: "Bald verfügbar", accessDenied: "Zugriff verweigert", demoText: "Hallo, dies ist eine kostenlose Demo der Vexa KI-Stimme" },
  tr: { moreVoices: "Daha fazla ses", chooseLanguageTitle: "🌐 <b>Dil seç</b>", chooseLanguageSubtitle: "Devam etmek için dilini seç", ttsTitle: "🎧 <b>Metinden sese</b>", sendText: "Metnini gönder", creditRule: "TTS ücreti karakter başına <b>$0.00017</b>", selectedVoice: "Seçilen ses", demo: "▶ Demo", next: "İleri →", previous: "← Geri", balance: "💎 Bakiye", buyCredits: "⚡ Bakiye yükle", choosePayment: "Ödeme yöntemi seç", buyToman: "🇮🇷 Toman ile öde", telegramStars: "⭐ Telegram Stars", back: "← Geri", cancel: "İptal", generatingDemo: "Demo oluşturuluyor", generatingVoice: "Ses oluşturuluyor", comingSoon: "Yakında", accessDenied: "Erişim reddedildi", demoText: "Merhaba, bu Vexa yapay zeka sesinin ücretsiz demosudur" },
  ar: { moreVoices: "المزيد من الأصوات", chooseLanguageTitle: "🌐 <b>اختر اللغة</b>", chooseLanguageSubtitle: "اختر لغتك للمتابعة", ttsTitle: "🎧 <b>تحويل النص إلى صوت</b>", sendText: "أرسل النص", creditRule: "تكلفة TTS هي <b>$0.00017 لكل حرف</b>", selectedVoice: "الصوت المختار", demo: "▶ تجربة", next: "التالي →", previous: "← السابق", balance: "💎 الرصيد", buyCredits: "⚡ شحن الرصيد", choosePayment: "اختر طريقة الدفع", buyToman: "🇮🇷 الدفع بالتومان", telegramStars: "⭐ نجوم تيليجرام", back: "← رجوع", cancel: "إلغاء", generatingDemo: "جاري إنشاء التجربة", generatingVoice: "جاري إنشاء الصوت", comingSoon: "قريباً", accessDenied: "تم رفض الوصول", demoText: "مرحباً، هذا عرض مجاني لصوت فيكسا بالذكاء الاصطناعي" },
  zh: { moreVoices: "更多声音", chooseLanguageTitle: "🌐 <b>选择语言</b>", chooseLanguageSubtitle: "请选择语言继续", ttsTitle: "🎧 <b>文字转语音</b>", sendText: "发送你的文本", creditRule: "TTS 每个字符收费 <b>$0.00017</b>", selectedVoice: "已选声音", demo: "▶ 试听", next: "下一页 →", previous: "← 上一页", balance: "💎 余额", buyCredits: "⚡ 充值余额", choosePayment: "选择支付方式", buyToman: "🇮🇷 使用 Toman 支付", telegramStars: "⭐ Telegram Stars", back: "← 返回", cancel: "取消", generatingDemo: "正在生成试听", generatingVoice: "正在生成语音", comingSoon: "即将推出", accessDenied: "拒绝访问", demoText: "你好，这是 Vexa 人工智能语音的免费试听" },
  ja: { moreVoices: "さらに音声", chooseLanguageTitle: "🌐 <b>言語を選択</b>", chooseLanguageSubtitle: "続行する言語を選択してください", ttsTitle: "🎧 <b>テキスト読み上げ</b>", sendText: "テキストを送信", creditRule: "TTS は1文字あたり <b>$0.00017</b>", selectedVoice: "選択中の音声", demo: "▶ デモ", next: "次へ →", previous: "← 戻る", balance: "💎 残高", buyCredits: "⚡ 残高をチャージ", choosePayment: "支払い方法を選択", buyToman: "🇮🇷 Tomanで支払う", telegramStars: "⭐ Telegram Stars", back: "← 戻る", cancel: "キャンセル", generatingDemo: "デモ生成中", generatingVoice: "音声生成中", comingSoon: "近日公開", accessDenied: "アクセス拒否", demoText: "こんにちは、これは Vexa AI 音声の無料デモです" },
  es: { moreVoices: "Más voces", chooseLanguageTitle: "🌐 <b>Elige tu idioma</b>", chooseLanguageSubtitle: "Selecciona tu idioma para continuar", ttsTitle: "🎧 <b>Texto a voz</b>", sendText: "Envía tu texto", creditRule: "TTS cuesta <b>$0.00017 por carácter</b>", selectedVoice: "Voz seleccionada", demo: "▶ Demo", next: "Siguiente →", previous: "← Anterior", balance: "💎 Saldo", buyCredits: "⚡ Recargar saldo", choosePayment: "Elige un método de pago", buyToman: "🇮🇷 Pagar con Toman", telegramStars: "⭐ Telegram Stars", back: "← Volver", cancel: "Cancelar", generatingDemo: "Generando demo", generatingVoice: "Generando voz", comingSoon: "Próximamente", accessDenied: "Acceso denegado", demoText: "Hola, esta es una demostración gratuita de la voz de inteligencia artificial de Vexa" },
  hi: { moreVoices: "और आवाज़ें", chooseLanguageTitle: "🌐 <b>भाषा चुनें</b>", chooseLanguageSubtitle: "जारी रखने के लिए अपनी भाषा चुनें", ttsTitle: "🎧 <b>टेक्स्ट टू स्पीच</b>", sendText: "अपना टेक्स्ट भेजें", creditRule: "TTS की कीमत प्रति अक्षर <b>$0.00017</b> है", selectedVoice: "चुनी गई आवाज़", demo: "▶ डेमो", next: "आगे →", previous: "← पीछे", balance: "💎 बैलेंस", buyCredits: "⚡ बैलेंस जोड़ें", choosePayment: "पेमेंट तरीका चुनें", buyToman: "🇮🇷 Toman से भुगतान", telegramStars: "⭐ Telegram Stars", back: "← वापस", cancel: "रद्द करें", generatingDemo: "डेमो बन रहा है", generatingVoice: "आवाज़ बन रही है", comingSoon: "जल्द आ रहा है", accessDenied: "एक्सेस मना है", demoText: "नमस्ते, यह Vexa एआई आवाज़ का मुफ्त डेमो है" },
};

export function normalizeLang(lang) { return LANGUAGES[lang] ? lang : "en"; }
export function t(lang, key, vars = {}) {
  const code = normalizeLang(lang || "en");
  let text = M[code]?.[key] || M.en[key] || key;
  const values = { ...vars };
  if (key === "balancePopup" && values.balance != null) {
    values.balance = formatUsdBalanceFromCredits(values.balance);
  }
  if (key === "notEnough") {
    if (values.needed != null) values.needed = formatUsdChargeFromCredits(values.needed);
    if (values.balance != null) values.balance = formatUsdBalanceFromCredits(values.balance);
  }
  for (const [k, v] of Object.entries(values)) text = text.replaceAll("{" + k + "}", String(v));
  return text;
}
