export const LANGUAGES = {
  en: "English",
  ru: "Русский",
  de: "Deutsch",
  fa: "فارسی",
  tr: "Türkçe",
  ar: "العربية",
  zh: "中文",
  ja: "日本語",
  es: "Español",
  hi: "हिन्दी",
};

const M = {
  en: {
    chooseLanguageTitle: "🌐 <b>Choose your language</b>", chooseLanguageSubtitle: "Please select your language to continue", ttsTitle: "🎧 <b>Text to Speech</b>", sendText: "Send your text", creditRule: "Each character uses <b>1 credit</b>", selectedVoice: "Selected voice", demo: "▶ Demo", next: "Next →", previous: "← Previous", balance: "💎 Balance", buyCredits: "⚡ Buy Credits", balancePopup: "Your balance:\n\n{balance} credits", buyTitle: "💳 <b>Buy Credits</b>", priceLine: "1000 credits = <b>$0.24</b>", choosePayment: "Choose a payment method", buyToman: "🇮🇷 Buy with Toman", telegramStars: "⭐ Telegram Stars", back: "← Back", buyTomanTitle: "🇮🇷 <b>Buy with Toman</b>", choosePackage: "Choose your credit package", almostThere: "🔥 <b>Almost there!</b>", package: "Package", amount: "Amount", transfer: "Please transfer the exact amount to this card number:", sendScreenshot: "Then send your payment screenshot right here", verification: "Your credits will be added after verification", cancel: "Cancel", generatingDemo: "Generating demo", generatingVoice: "Generating voice", notEnough: "Not enough credits\nNeeded: {needed} credits\nBalance: {balance} credits", screenshotNoPackage: "Screenshot received. If this is for a credit purchase, please choose a package first", screenshotReceived: "✅ <b>Payment screenshot received!</b>", receiptWaiting: "Your receipt is now waiting for admin verification", creditsAfterApproval: "After approval, your credits will be added to your balance", keepUsing: "You can keep using the bot or choose another option below", comingSoon: "Coming soon", invalidPackage: "Invalid package", ttsError: "TTS Error", accessDenied: "Access denied"
  },
  fa: { chooseLanguageTitle: "🌐 <b>زبان را انتخاب کن</b>", chooseLanguageSubtitle: "برای ادامه زبان خودت را انتخاب کن", ttsTitle: "🎧 <b>تبدیل متن به صدا</b>", sendText: "متنت را بفرست", creditRule: "هر کاراکتر <b>۱ کردیت</b> مصرف می‌کند", selectedVoice: "صدای انتخاب‌شده", demo: "▶ دمو", next: "بعدی →", previous: "← قبلی", balance: "💎 موجودی", buyCredits: "⚡ خرید کردیت", balancePopup: "موجودی شما:\n\n{balance} کردیت", buyTitle: "💳 <b>خرید کردیت</b>", priceLine: "۱۰۰۰ کردیت = <b>$0.24</b>", choosePayment: "روش پرداخت را انتخاب کن", buyToman: "🇮🇷 خرید با تومان", telegramStars: "⭐ استارز تلگرام", back: "← برگشت", buyTomanTitle: "🇮🇷 <b>خرید با تومان</b>", choosePackage: "پکیج کردیت را انتخاب کن", almostThere: "🔥 <b>تقریباً تمومه!</b>", package: "پکیج", amount: "مبلغ", transfer: "مبلغ دقیق را به این شماره کارت واریز کن:", sendScreenshot: "بعد اسکرین‌شات پرداخت را همینجا بفرست", verification: "بعد از تایید، کردیت‌ها اضافه می‌شوند", cancel: "لغو", generatingDemo: "در حال ساخت دمو", generatingVoice: "در حال ساخت صدا", notEnough: "کردیت کافی نداری\nنیاز: {needed} کردیت\nموجودی: {balance} کردیت", screenshotNoPackage: "اسکرین‌شات دریافت شد. اول یک پکیج انتخاب کن", screenshotReceived: "✅ <b>اسکرین‌شات پرداخت دریافت شد!</b>", receiptWaiting: "رسید شما منتظر تایید ادمین است", creditsAfterApproval: "بعد از تایید، کردیت‌ها اضافه می‌شوند", keepUsing: "می‌توانی از ربات استفاده کنی یا گزینه‌ای انتخاب کنی", comingSoon: "به‌زودی", invalidPackage: "پکیج نامعتبر است", ttsError: "خطای تبدیل صدا", accessDenied: "دسترسی غیرمجاز" },
  ru: { chooseLanguageTitle: "🌐 <b>Выберите язык</b>", chooseLanguageSubtitle: "Выберите язык, чтобы продолжить", ttsTitle: "🎧 <b>Текст в речь</b>", sendText: "Отправьте текст", creditRule: "Каждый символ использует <b>1 кредит</b>", selectedVoice: "Выбранный голос", demo: "▶ Демо", next: "Далее →", previous: "← Назад", balance: "💎 Баланс", buyCredits: "⚡ Купить кредиты", choosePayment: "Выберите способ оплаты", buyToman: "🇮🇷 Оплата в томанах", telegramStars: "⭐ Telegram Stars", back: "← Назад", cancel: "Отмена", generatingDemo: "Создаю демо", generatingVoice: "Создаю голос", comingSoon: "Скоро", accessDenied: "Доступ запрещен" },
  de: { chooseLanguageTitle: "🌐 <b>Sprache wählen</b>", chooseLanguageSubtitle: "Bitte wähle deine Sprache", ttsTitle: "🎧 <b>Text zu Sprache</b>", sendText: "Sende deinen Text", creditRule: "Jedes Zeichen kostet <b>1 Credit</b>", selectedVoice: "Ausgewählte Stimme", demo: "▶ Demo", next: "Weiter →", previous: "← Zurück", balance: "💎 Guthaben", buyCredits: "⚡ Credits kaufen", choosePayment: "Zahlungsmethode wählen", buyToman: "🇮🇷 Mit Toman kaufen", telegramStars: "⭐ Telegram Stars", back: "← Zurück", cancel: "Abbrechen", generatingDemo: "Demo wird erstellt", generatingVoice: "Stimme wird erstellt", comingSoon: "Bald verfügbar", accessDenied: "Zugriff verweigert" },
  tr: { chooseLanguageTitle: "🌐 <b>Dil seç</b>", chooseLanguageSubtitle: "Devam etmek için dilini seç", ttsTitle: "🎧 <b>Metinden sese</b>", sendText: "Metnini gönder", creditRule: "Her karakter <b>1 kredi</b> kullanır", selectedVoice: "Seçilen ses", demo: "▶ Demo", next: "İleri →", previous: "← Geri", balance: "💎 Bakiye", buyCredits: "⚡ Kredi satın al", choosePayment: "Ödeme yöntemi seç", buyToman: "🇮🇷 Toman ile satın al", telegramStars: "⭐ Telegram Stars", back: "← Geri", cancel: "İptal", generatingDemo: "Demo oluşturuluyor", generatingVoice: "Ses oluşturuluyor", comingSoon: "Yakında", accessDenied: "Erişim reddedildi" },
  ar: { chooseLanguageTitle: "🌐 <b>اختر اللغة</b>", chooseLanguageSubtitle: "اختر لغتك للمتابعة", ttsTitle: "🎧 <b>تحويل النص إلى صوت</b>", sendText: "أرسل النص", creditRule: "كل حرف يستخدم <b>1 رصيد</b>", selectedVoice: "الصوت المختار", demo: "▶ تجربة", next: "التالي →", previous: "← السابق", balance: "💎 الرصيد", buyCredits: "⚡ شراء رصيد", choosePayment: "اختر طريقة الدفع", buyToman: "🇮🇷 الدفع بالتومان", telegramStars: "⭐ نجوم تيليجرام", back: "← رجوع", cancel: "إلغاء", generatingDemo: "جاري إنشاء التجربة", generatingVoice: "جاري إنشاء الصوت", comingSoon: "قريباً", accessDenied: "تم رفض الوصول" },
  zh: { chooseLanguageTitle: "🌐 <b>选择语言</b>", chooseLanguageSubtitle: "请选择语言继续", ttsTitle: "🎧 <b>文字转语音</b>", sendText: "发送你的文本", creditRule: "每个字符消耗 <b>1 credit</b>", selectedVoice: "已选声音", demo: "▶ 试听", next: "下一页 →", previous: "← 上一页", balance: "💎 余额", buyCredits: "⚡ 购买 Credits", choosePayment: "选择支付方式", buyToman: "🇮🇷 使用 Toman 购买", telegramStars: "⭐ Telegram Stars", back: "← 返回", cancel: "取消", generatingDemo: "正在生成试听", generatingVoice: "正在生成语音", comingSoon: "即将推出", accessDenied: "拒绝访问" },
  ja: { chooseLanguageTitle: "🌐 <b>言語を選択</b>", chooseLanguageSubtitle: "続行する言語を選択してください", ttsTitle: "🎧 <b>テキスト読み上げ</b>", sendText: "テキストを送信", creditRule: "1文字につき <b>1 credit</b> 消費", selectedVoice: "選択中の音声", demo: "▶ デモ", next: "次へ →", previous: "← 戻る", balance: "💎 残高", buyCredits: "⚡ Credits購入", choosePayment: "支払い方法を選択", buyToman: "🇮🇷 Tomanで購入", telegramStars: "⭐ Telegram Stars", back: "← 戻る", cancel: "キャンセル", generatingDemo: "デモ生成中", generatingVoice: "音声生成中", comingSoon: "近日公開", accessDenied: "アクセス拒否" },
  es: { chooseLanguageTitle: "🌐 <b>Elige tu idioma</b>", chooseLanguageSubtitle: "Selecciona tu idioma para continuar", ttsTitle: "🎧 <b>Texto a voz</b>", sendText: "Envía tu texto", creditRule: "Cada carácter usa <b>1 crédito</b>", selectedVoice: "Voz seleccionada", demo: "▶ Demo", next: "Siguiente →", previous: "← Anterior", balance: "💎 Saldo", buyCredits: "⚡ Comprar créditos", choosePayment: "Elige un método de pago", buyToman: "🇮🇷 Comprar con Toman", telegramStars: "⭐ Telegram Stars", back: "← Volver", cancel: "Cancelar", generatingDemo: "Generando demo", generatingVoice: "Generando voz", comingSoon: "Próximamente", accessDenied: "Acceso denegado" },
  hi: { chooseLanguageTitle: "🌐 <b>भाषा चुनें</b>", chooseLanguageSubtitle: "जारी रखने के लिए अपनी भाषा चुनें", ttsTitle: "🎧 <b>टेक्स्ट टू स्पीच</b>", sendText: "अपना टेक्स्ट भेजें", creditRule: "हर अक्षर <b>1 credit</b> इस्तेमाल करता है", selectedVoice: "चुनी गई आवाज़", demo: "▶ डेमो", next: "आगे →", previous: "← पीछे", balance: "💎 बैलेंस", buyCredits: "⚡ Credits खरीदें", choosePayment: "पेमेंट तरीका चुनें", buyToman: "🇮🇷 Toman से खरीदें", telegramStars: "⭐ Telegram Stars", back: "← वापस", cancel: "रद्द करें", generatingDemo: "डेमो बन रहा है", generatingVoice: "आवाज़ बन रही है", comingSoon: "जल्द आ रहा है", accessDenied: "एक्सेस मना है" },
};

export function normalizeLang(lang) { return LANGUAGES[lang] ? lang : "en"; }
export function t(lang, key, vars = {}) {
  const code = normalizeLang(lang || "en");
  let text = M[code]?.[key] || M.en[key] || key;
  for (const [k, v] of Object.entries(vars)) text = text.replaceAll("{" + k + "}", String(v));
  return text;
}
